### ISSUE TITLE
OpenTelemetry Support

### ISSUE THREAD

**Issue by alhardy** [DataDog/dd-trace-dotnet#1043]
**Are you requesting automatic instrumentation for a framework or library? Please describe.**
Are there plans to implement an OpenTelemetry exporter and automatic instrumentation?

**Describe the solution you'd like**
DataDog OpenTelemetry exporter.

**Comment by mrxrsd** [comment]
Is anyone aware of a planned data Dog exporter? I've saw there are others languages but dotnet not yet.

**Comment by mrtaikandi** [comment]
Any update on this?

**Comment by lucaspimentel** [comment]
Instead of using a .NET OpenTelemetry exporter for Datadog, you can use the standard OTLP protocol to send traces and metrics to the Datadog Agent.

Read more about OTLP:
- [OpenTelemetry Protocol Specification](https://github.com/open-telemetry/oteps/blob/main/text/0035-opentelemetry-protocol.md)

Configure the OTLP exporter in your app:
- [OpenTelemetry: Docs / Instrumentation / .NET / Exporters](https://opentelemetry.io/docs/instrumentation/net/exporters/#otlp-endpoint-or-collector)

Configure the Datadog Agent to receive data via OTLP:
- [Datadog: OTLP Trace Ingestion by the Datadog Agent](https://docs.datadoghq.com/tracing/trace_collection/open_standards/otlp_ingest_in_the_agent/)
