### ISSUE TITLE
Support for ARM64 - Debian

### ISSUE THREAD

**Issue by npetter** [DataDog/dd-trace-dotnet#1070]
**Are you requesting automatic instrumentation for a framework or library? Please describe.**
No

**Is your feature request related to a problem? Please describe.**
We're running more and more workloads on AWS Graviton 2 -> ARM64 machines. We're unable to move
asp.net core applications until there's a arm64 deb package.

**Describe the solution you'd like**
Some way to install a tracer built for ARM64.

**Additional context**
We've so far been using the official .net core "3.1.10-buster-slim-arm64v8" images, and will migrate to 5.0 some time in the future.

**Comment by kevingosse** [comment]
Hello,

We're evaluating the amount of work needed to make this happen. One of our concerns is that the profiling API [is not officially supported on ARM64](https://github.com/dotnet/runtime/blob/master/docs/project/profiling-api-status.md) so we need to figure out exactly what works and what doesn't. We'll keep this issue updated as we get more visibility on the subject.

**Comment by DerrickMartinez** [comment]
Anything on this? Might have to consider something else than DD for our APM needs...

**Comment by DerrickMartinez** [comment]
According to them "Profiling is fully supported for Linux and Windows on arm64 as of .Net 5.0. Everything but ELT hooks is supported in 3.1, and releases prior to 3.1 are untested by Microsoft. Let me know if you have any other questions."

**Comment by kevingosse** [comment]
Current state of ARM64 support: 

- We have a working PoC. There is a pending PR to update our build pipeline to produce artifacts for ARM64 and run our integration tests: https://github.com/DataDog/dd-trace-dotnet/pull/1114
- Support will start at .NET 5. ReJIT APIs don't work on .NET Core 3.1 with ARM64, and we're going to need them in the near future
- Because we're still discussing how to properly test the ARM64 bits, I can't give a schedule for rollout yet

If there are other customers interested in ARM64 support, please comment on this issue, it helps us prioritizing versus other items.

**Comment by vietthanhnexle** [comment]
Please support this one. We also have a plan to move to AWS Graviton2.
Thank you.

**Comment by andrewlock** [comment]
The [latest release](https://github.com/DataDog/dd-trace-dotnet/releases/latest) of the .NET Tracer includes Linux ARM64 support. As noted [in a previous comment](https://github.com/DataDog/dd-trace-dotnet/issues/1070#issuecomment-758551001), automatic instrumentation on ARM64 requires .NET 5. 

Thanks for the input, any problems, feel free to raise a new issue.
