### ISSUE TITLE
Error creating native log file message logged when no FileLogger is registered with Serilog

### ISSUE THREAD

**Issue by d1820** [DataDog/dd-trace-dotnet#1484]
When setting up DataDog with Serilog in .Net an error is thrown an every deployment when no File sinks are registered with Serilog. We are seeing an additional 150+ messages an hour from all our services related to the error:  "Logger Handler: Error creating native log file."

Based on the following docs
https://docs.datadoghq.com/tracing/connect_logs_and_traces/dotnet/?tab=serilog

it shows using a WriteTo.File. In our case we are only logging to console for our kubernetes cluster and getting the traces from there

```
var loggerConfiguration = new LoggerConfiguration().Enrich.FromLogContext();
loggerConfiguration.WriteTo.Console(new RenderedCompactJsonFormatter());
Log.Logger = loggerConfiguration.CreateLogger();
logging.AddSerilog(Log.Logger, dispose: true); //logging here is the .net ILoggingBuilder
```

On deployment based on the code
https://github.com/DataDog/dd-trace-dotnet/blob/master/src/Datadog.Trace.ClrProfiler.Native/logging.cpp
```
 try {
    m_fileout = spdlog::rotating_logger_mt(
        "Logger", GetLogPath(file_name_suffix), 1048576 * 5, 10);
  }
  catch (...) {
    std::cerr << "Logger Handler: Error creating native log file." << std::endl;
    m_fileout = spdlog::null_logger_mt("Logger");
  }
```

it seems to be expecting file logging which is not always the case

**Expected behavior**
If WriteTo.File is not used it should not try to get a logPath and log a stdErr. This fills Datadog with tons of messages, that have no impact on the real traces being logged. Dont log an error if no file sink is registered

**Screenshots**

**Runtime environment (please complete the following information):**
- Datadog.Trace 1.26.3
- Ubuntu
- .NET Core 5
- Nugets
```
<PackageReference Include="Datadog.Trace" Version="1.26.3" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.2.7" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="2.0.2" />
    <PackageReference Include="Serilog.Formatting.Compact" Version="1.1.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="3.1.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
```

<!--
NOTE: To contact our support team, see https://www.datadoghq.com/support/
When contacting support, please include the information requested above.
If possible, also include the tracer log files found (by default) in:
Windows: %ProgramData%\Datadog .NET Tracer\logs\
Linux: /var/log/datadog/dotnet/
--!>

**Comment by andrewlock** [comment]
Thanks for flagging this, I can understand the frustration there. 

Just to clarify a couple of points. There are currently two different "types" of log messages at play here:
* _Application_ logs: These are written using Serilog [as shown in the documentation you linked](https://docs.datadoghq.com/tracing/connect_logs_and_traces/dotnet/?tab=serilog). These are the logs that your application writes which the Datadog tracer enriches with `TraceId` and other properties. 
* _Tracer_ Logs: These are written by the Datadog tracer for monitoring and debugging purposes. These are always written to file, [as described in this section of the documentation](https://docs.datadoghq.com/tracing/troubleshooting/tracer_debug_logs). These are completely separate from your application logs, and do not use the same Serilog configuration in your application.

The issue you're seeing is related to the _tracer_ log files, so it is unrelated to your Serilog configuration. In your case, the Tracer isn't able to write to the log folder (`/var/log/datadog/dotnet/` on Linux) for some reason, so we raise that error.

I have a few questions to get to the root cause:

* Are you running directly in Ubuntu, or inside a container?
* If in a docker container, are you using a read only filesystem (`docker run --read-only`)?
* After installing the _.deb_ file, [did you run the `/opt/datadog/createLogPath.sh` script](https://docs.datadoghq.com/tracing/setup_overview/setup/dotnet-core/?tab=linux#installing-the-tracer)?
* Can you confirm whether the directory `/var/log/datadog/dotnet/` exists?
* If not, could you run the  `/opt/datadog/createLogPath.sh` and confirm whether that resolves your problem?

**Comment by d1820** [comment]
@adammck Thanks for the information and clarification. We needed to roll into our image the running of the script ```/opt/datadog/createLogPath.sh```. This resolved our issue.

**Comment by andrewlock** [comment]
Glad to hear it, and glad you resolved the issue!
