### ISSUE TITLE
Logs and traces are no longer connected after upgrading to version 1.27.0

### ISSUE THREAD

**Issue by mupuri** [DataDog/dd-trace-dotnet#1534]
**Describe the bug**
When we upgraded the dd-tracer-dotnet to version 1.27.0, logs and traces are no longer correlated. When we downgrade down to version 1.26.3, the correlation starts working again.

We have set the following environment variables:
DD_ENV
DD_SERVICE
DD_VERSION

We are running the datadog agent in kubernetes as a daemonset using the datadog helm chart.

Is there any change in 1.27.0 that we are missing?

**Expected behavior**
Logs and traces are connected in datadog.

**Screenshots**
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/57722219/121961019-b934fa00-cd1b-11eb-9f6b-8078ad8843e1.png">

**Runtime environment (please complete the following information):**
- Instrumentation mode: automatic
- Tracer version: 1.27.0
- OS: Linux
- CLR: .NET 5.0
- Cluster agent helm chart: helm.sh/chart=datadog-2.8.1
- Datadog agent image: gcr.io/datadoghq/agent:7.25.0

**Comment by lucaspimentel** [comment]
Hello, @mupuri. For logs correlation to work, trace IDs and spans IDs must be injected into your application logs. Configuration is different if you are doing manually or if the tracer is injecting these values automatically. See [Connecting .NET Logs and Traces](https://docs.datadoghq.com/tracing/connect_logs_and_traces/dotnet) for more details.

However, since you can see logs correlation working when you downgrade to 1.26.3, it seems that this is not a configuration issue. Can you create a support ticket by emailing support@datadoghq.com so we can collect more detailed information about your specific configuration? Please include a link to this github issue and my name so it can be routed as quickly as possible. Thanks!

**Comment by suchitsubramanianTR** [comment]
I can confirm we are facing the same issue after upgrading to 1.27.1 as well.

**Comment by mupuri** [comment]
@lucaspimentel I created a support ticket like you requested. This is the request number: 511073

**Comment by suchitsubramanianTR** [comment]
@lucaspimentel I also created a support case to track this. Request # is 516970

**Comment by kevingosse** [comment]
I'm struggling to reproduce the issue.

What I've done is:
 - Setup a new aspnetcore application
 - Configure the logger with:
```csharp
            Log.Logger = new LoggerConfiguration()
                .Enrich.FromLogContext()
                .Enrich.WithMachineName()
                .WriteTo.Console(new JsonFormatter(), LogEventLevel.Information)
                .CreateLogger();
```
 - Configure the aspnetcore builder with:
```csharp
        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseSerilog()
                .UseUrls("http://localhost:6661")
                .UseStartup<Startup>();
```
 - Launch the app with the default tracer environment variables and `DD_LOGS_INJECTION=1`

Do you see anything fundamentally different in the way you setup the logging or the tracer?

**Comment by kevingosse** [comment]
Never mind, I think I found the issue.

When log injection is initialized, we scan for log libraries and instrument the first we find.
In 1.26.* (and previous versions) we were scanning in the order:
- Serilog
- NLog
- Log4Net

In 1.27.* we (involuntarily) changed the order to:
- Log4net
- NLog
- Serilog

 It means that if log4net is somehow loaded (likely though a transitive dependency), in 1.27.* we will instrument that library instead of Serilog.

In the next version of the tracer we will revert the order.

**Comment by suchitsubramanianTR** [comment]
I know that we load log4net via a transitive dependency. That is definitely the issue.

**Comment by mupuri** [comment]
@kevingosse thank you for looking into this. I looked at our dependency graph and looks like we were also pulling in log4net from another dependency

**Comment by suchitsubramanianTR** [comment]
@kevingosse Do we have any ETA on 1.28.0?

**Comment by kevingosse** [comment]
Version 1.28.0 has been released. Feel free to re-open this issue if the fix doesn't work for you.

**Comment by mupuri** [comment]
Updating to 1.28.0 fixed the issue for us. Thank you!

**Comment by suchitsubramanianTR** [comment]
I can confirm it's working for us as well. Thanks @kevingosse
