### ISSUE TITLE
Wrong Resourcename when UseExceptionHandler is used

### ISSUE THREAD

**Issue by lippinio** [DataDog/dd-trace-dotnet#1643]
**Description**

In a dotnet application UseExceptionHandler is an extensionmethod, that provides the possiblity to handle exceptions. 
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-5.0#exception-handler-page

The Problem seems to be that the Datadogtracer can't extract the resourcename properly when UseExceptionHandler is used. On spans with an error the resourcename always points to the errorhandler endpoint. That leads to incorrect errorrate due that errors are reported on the errorendpoint instead of the actual failling endpoint.

**To Reproduce**
This repo contains a standard dotnet application with the errorhandling implemented as described by microsoft.
https://github.com/lippinio/ErrorControllerExample/tree/main
The endpoint https://localhost:5001/Home/Fancy is built so produce sometimes an error. This error is handled by the implemented errorhandler. Now in Datadog are 2 Endpoints visible first the Fancy Endpoint with no errors and the errorhandler endpoint with 100% errors.

**Expected behavior**
I would like to see that the actual resourcename that produces the error is set as resourcename in datadog

**Screenshots**
![image](https://user-images.githubusercontent.com/36662277/127643268-0fd7e6cc-6419-4e5e-bf6e-f185481b953b.png)

**Runtime environment (please complete the following information):**
- Instrumentation mode: Automatic instrumentation 
- Tracer version: 1.28
- OS: Any
- CLR: dotnet 5

**Comment by andrewlock** [comment]
Hi @lippinio,

The problem you're describing is one we're aware of, which unfortunately we weren't able to correct as it was technically a breaking change. 

However, we have a feature flag, `DD_TRACE_ROUTE_TEMPLATE_RESOURCE_NAMES_ENABLED`, (available since version 1.26.0), which corrects this problem. The feature flag changes the resource names to use route templates instead of `Controller/Action`, handles endpoint routing properly, and handles pipeline re-execution (the issue you're describing).

To confirm, I pulled down your sample (thanks for providing that, it makes confirming so much easier!), set the environment variable `DD_TRACE_ROUTE_TEMPLATE_RESOURCE_NAMES_ENABLED=true`, and hit the fancy endpoint. I get the following:

![image](https://user-images.githubusercontent.com/18755388/127647322-e13a143d-e839-44a8-a70c-7981a68b464c.png)

Note that there is only one resource name shown, some with 200, and some with 500 status codes. 

Where possible, I suggest using the updated resource names (we will likely enable them by default in a future version). Just be aware that this will change the resource names for endpoints, so you may need to update and corresponding monitors/dashboards.

**Comment by andrewlock** [comment]
Hopefully this solves your problem @lippinio. Feel free to reopen if that doesn't work 🙂
