### ISSUE TITLE
LoggerImpl Handler: Error creating native log file.

### ISSUE THREAD

**Issue by jrmccannon** [DataDog/dd-trace-dotnet#1676]
**Describe the bug**
When starting up my .NET 5 project, I receive the following error.
```
LoggerImpl Handler: Error creating native log file.
```

**To Reproduce**
1. Created a brand new .NET 5 Console Application
2. Added dockerfile with the following datadog information per the documentation.
```
RUN curl -LO https://github.com/DataDog/dd-trace-dotnet/releases/download/v1.28.2/datadog-dotnet-apm_1.28.2_amd64.deb
RUN dpkg -i ./datadog-dotnet-apm_1.28.2_amd64.deb

ENV CORECLR_ENABLE_PROFILING=1
ENV CORECLR_PROFILER={846F5F1C-F9AE-4B07-969E-05C26BC060D8}
ENV CORECLR_PROFILER_PATH=/opt/datadog/Datadog.Trace.ClrProfiler.Native.so
ENV DD_INTEGRATIONS=/opt/datadog/integrations.json
ENV DD_DOTNET_TRACER_HOME=/opt/datadog
```

**Expected behavior**
I expected it to start up without a problem.

**Runtime environment (please complete the following information):**
- Instrumentation mode: Automatic
- Tracer version: 1.28.2
- OS: Linux
- CLR: .NET 5

**Additional context**
I'm running this is a linux docker container using the .NET 5 runtime.
```
FROM mcr.microsoft.com/dotnet/runtime:5.0 AS base
```

**Workaround**
If I add the trace log path environment variable and set it to the default datadog trace location, it works fine.

Here's a link to a github project with the example.
https://github.com/jrmccannon/datadog-1.28.2-test

**Comment by andrewlock** [comment]
Hi @jrmccannon, thanks for reaching out. 

I think you're missing a line in your Dockerfile that runs the script (included in the deb file) that creates the log path and updates permissions (as described in [the docs](https://docs.datadoghq.com/tracing/setup_overview/setup/dotnet-core/?tab=linux#compatibility-requirements)). For example, you should have something like:

```docker
RUN curl -LO https://github.com/DataDog/dd-trace-dotnet/releases/download/v1.28.2/datadog-dotnet-apm_1.28.2_amd64.deb
RUN dpkg -i ./datadog-dotnet-apm_1.28.2_amd64.deb

# Add this line 
RUN chmod +x /opt/datadog/createLogPath.sh && /opt/datadog/createLogPath.sh

# ... other variables as before
```

This creates the default log directory (`/var/log/datadog/dotnet`) and adds permissions to write to the directory, alternatively, you can set the log path to an existing directory using `DD_TRACE_LOG_DIRECTORY` as you mentioned.

The behaviour changed in [this PR](https://github.com/DataDog/dd-trace-dotnet/pull/1625) to print to stderr when we can't write logs. We will [revert that behaviour](https://github.com/DataDog/dd-trace-dotnet/pull/1677) so that we don't print to stderr on startup, but you will still want to create the log directory nevertheless 🙂

**Comment by jrmccannon** [comment]
Whoops. Sorry missed that line in the docs. Thanks for answering so quickly. I'll add that to my file.

Thanks again!

**Comment by andrewlock** [comment]
No problem, thanks for flagging the change in behaviour! 🙂

**Comment by lucianoeger** [comment]
Hi, I'm having the same problem, but in my case I'm testing the new CI feature (testing visibility) with Azure DevOps.
Would the solution look like the above case?

**Comment by andrewlock** [comment]
Hi @lucianoeger, yes, the solution will be the same  - either create the default log path at `/var/log/datadog/dotnet` and ensure it is writeable (the easiest way is by running the `createLogPath.sh` included in the linux packages) or set a different (existing) directory using the `DD_TRACE_LOG_DIRECTORY` environment variable. We have [merged a fix](https://github.com/DataDog/dd-trace-dotnet/pull/1677) for the issue, which should be included in the next release, but we advise you take the above steps regardless 🙂
