### ISSUE TITLE
AdoNet DbCommand instrumentation no longer working

### ISSUE THREAD

**Issue by gc-dev1** [DataDog/dd-trace-dotnet#1973]
**Describe the bug**
After updating Datadog.Trace from `1.26.2` to `1.29.0`, the automatic instrumentation is no longer picking up `AdoNet.DbCommand`.

I provided partial logs containing some key information, to compare previous JIT compiling.
If you need more details or information - please let me know.

Thank you for any help.

**Runtime environment:**
- Instrumentation mode: automatic with msi installer and manual with NuGet package
- Tracer version: 1.29.0
- OS: Windows Server 2019
- CLR: .NET Framework 4.8, Windows Service & IIS

[dd-trace-log-1.26.2.log](https://github.com/DataDog/dd-trace-dotnet/files/7449791/dd-trace-log-1.26.2.log)
[dd-trace-log-1.29.0.log](https://github.com/DataDog/dd-trace-dotnet/files/7449792/dd-trace-log-1.29.0.log)

**Comment by zacharycmontoya** [comment]
Hi @gc-dev1, thank you for the report and the two logs files. I took a look at the logs of 1.29.0 and it looks like the instrumentation of `System.Data.DbCommand` and `System.Data.SqlClient.SqlCommand` is happening correctly.

One *big* difference between the two versions is that starting with [.NET Tracer v1.28.0](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v1.28.0), our instrumentation defaults to `CallTarget` instrumentation instead of the previous `CallSite` instrumentation, which means we now instrument the specific methods themselves instead methods that call the specified library code. Is the lack of instrumentation occurring when making calls to `IBM.Data.Db2` commands like your previous [issue](https://github.com/DataDog/dd-trace-dotnet/issues/1494)? If so, then I suspect the issue is with `CallTarget` instrumentation which now requires a specific integration to target the `IBM.Data.Db2` types in order to get traces.

In the meantime, one way to restore the previous behavior of the .NET Tracer is to set the environment variable `DD_TRACE_CALLTARGET_ENABLED=false`, though this will undo many performance optimizations that have been made to the Tracer during this upgrade to latest.

**Comment by gc-dev1** [comment]
Hi @zacharycmontoya, thank you clearing this up.
I wasn't aware of this breaking change. This issue not directly related to #1494, even though both are using IBM DB2 related drivers. So I was a bit surprised when I updated dd-trace to 1.29.0 and the .NET 4.8 project (in this issue, using `IBM.Data.DB2.iSeries`) stopped working and the other .NET 5 project (using the entity framework #1494) worked just fine.

So I set `DD_TRACE_CALLTARGET_ENABLED=false` and it is working again. Which is good. So I don't have to rollback to 1.26.2 again.
Having this solved - is there any way, we can make use of this performance optimizations you've mentioned, in the future - without disabling `CallTarget`?

Thanks again for the quick "fix" :)

**Comment by gc-dev1** [comment]
Hi again @zacharycmontoya 
quick question: does setting `DD_TRACE_CALLTARGET_ENABLED=false` in IIS `web.config` have no effect in IIS site?

Because this seems to be the case right now. Am I missing something?

**Comment by zacharycmontoya** [comment]
Hi @gc-dev1 , that's correct. I apologize if our docs were not clear enough, but there are several settings that affect key parts of the automatic instrumentation (e.g. CLR Profiler Path, Call Target setting) and these environment variables MUST be set by environment variables. Setting them inside the .NET application has no effect because it is too late to change them.

To set this as an environment variable you can either set this a machine-level environment variable or set it in the registry so that only IIS processes receive them. That can be done by setting an `Environment` multiString registry value in the following locations:
- `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W3SVC`
- `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WAS`

**Comment by gc-dev1** [comment]
I was just about to edit my post... since I got it working now by setting a system wide environment variable like
`[System.Environment]::SetEnvironmentVariable('DD_TRACE_CALLTARGET_ENABLED','false',[System.EnvironmentVariableTarget]::Machine)` in PowerShell.

So this is working now. Thanks, for the quick reply.
And yes, it would be helpful to get every possible setting listed and explained in the docs. I use them quite often to check up on "how to do anything with Datadog" ;)

**Comment by andrewlock** [comment]
@gc-dev1 as mentioned #1494, the next version of the tracer (not yet released, after 2.0.1) we will instrument the `DbCommand` base class which should resolve this issue. Note that in version 2.0, CallTarget is the only supported mode, so you can remove any references to `DD_TRACE_CALLTARGET_ENABLED`
