### ISSUE TITLE
No automatic instrumentation within manually created spans when using App Service Extension

### ISSUE THREAD

**Issue by sevetseh28** [DataDog/dd-trace-dotnet#2151]
**Describe the bug**
I am deploying a .NET Core 5 API in App Service with the Extension v1.10.0. I am using Datadog.Trace 1.31.0 to manually create some spans. Issue is that all integrations-related spans are not automatically added within the spans I create, only in the REST endpoints.

**To Reproduce**
1. Deploy .NET Core App Service with the Extension 1.10.0 installed.
2. Manually create spans using the Datadog.Trace 1.31.0 lib and make an HTTP call or DB update within that span.
3. See that REST endpoints contain all the integration traces (like the DB hits) but all the DB queries or HTTP calls within the manually created Spans are not shown in datadog.

**Expected behavior**
I would expect all the auto-instrumented integrations to also appear within the manually created span.

**Runtime environment (please complete the following information):**
- Instrumentation mode: automatic with App Service Extension v1.10.0 and manual with this library.
- Tracer version: 1.31.0
- OS: App Service for Windows
- CLR: .NET Core 5

**Additional context**

<!--
NOTE: To contact our support team, see https://www.datadoghq.com/support/
When contacting support, please include the information requested above.
If possible, also include the tracer log files found (by default) in:
Windows: %ProgramData%\Datadog .NET Tracer\logs\
Linux: /var/log/datadog/dotnet/
--!>

**Comment by andrewlock** [comment]
Hi @sevetseh28, sorry for the delay reaching out.

The behaviour you're describing is a bit confusing. Specifically, it fits almost exactly the expected behaviour when there is a mismatch between the automatic-instrumentation version and the NuGet version. However, based on your description, you _don't_ have mismatched versions, as [AAS v1.10.0 includes tracer version 1.31.0](https://github.com/DataDog/datadog-aas-extension/releases/tag/v1.10.0). 

Would you be able to double check that these version numbers are definitely correct, as a mismatch there is the most likely explanation. Also, we have [since released v2.0.1 of the tracer](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v2.0.1) ([and corresponding v1.10.1 AAS extension](https://github.com/DataDog/datadog-aas-extension/releases/tag/v1.10.1), which includes a number of changes, including handling mismatched versions. It may be worth  seeing if that resolves your problem.

Failing that, it may be best to open a ticket with support by contacting support@datadoghq.com and referencing this GitHub issue, so we can collect all the necessary information to investigate further. 

Thank you!

**Comment by pierotibou** [comment]
Hello @sevetseh28, were you able to confirm the versions you were using? Do you still encounter the issue?
Thank you.

**Comment by pierotibou** [comment]
Hello, I'm closing this issue as it's been inactive.  
Obviously, don't hesitate to reopen it if need be.
Thank you
