### ISSUE TITLE
COR_ENABLE_PROFILING not mentioned in documentation

### ISSUE THREAD

**Issue by rlaveycal** [DataDog/dd-trace-dotnet#222]
**Describe the bug**

The documentation doesn't clearly mention that environment variables `COR_ENABLE_PROFILING` and `COR_PROFILER` need to be set in order to enable auto-tracing for non-IIS applications.

Perhaps the MSI should set these as well as `DD_INTEGRATIONS`

**Comment by lucaspimentel** [comment]
Thanks for the feedback, @rlaveycal. For our initial beta offering, we were focusing on a streamlined installation experience in Windows where things just magically work for web applications running on IIS. As we add support for more use cases (e.g. .NET Core, Linux), we've been adding those to our documentation (including the environment variables needed to enable the profiler). We will expand and improve the documentation to include manual configuration and more advanced scenarios as we get closer to GA.

As for the MSI installer, it sets the profiler environment variables for IIS automatically because most of our users want to trace web applications, and it is pretty safe to do so since it doesn't affect other processes on the host. If the MSI were to add the environment variables globally, we would try to attach the profiler to _all_ .NET applications on the host, which is not what our users want.

**Comment by rlaveycal** [comment]
@lucaspimentel do you have any thoughts about how the profiler can be enabled only for selected .Net apps? The apps we would want to trace are not hosted in IIS - they're Framework 4.7.1 Windows services. Your point about the env vars enabling global tracing is well made.

The MS docs say

>The profiler should add logic to its ICorProfilerCallback::Initialize callback to detect whether the current process is of interest. If it is not, the profiler can fail the callback without performing the initialization.

So I guess a section in the agent.yaml that can list the apps to be profiled might work?

**Comment by lucaspimentel** [comment]
> do you have any thoughts about how the profiler can be enabled only for selected [Windows services]?

For Windows Services, you can set the environment variables in the Windows Registry in the multi-string `HKLM\System\CurrentControlSet\Services\{service_name}\Environment` key. This is what [our MSI installer does](https://github.com/DataDog/dd-trace-dotnet/blob/9131814e57417f4285a52036d2263a5759e90cf4/deploy/Datadog.Trace.ClrProfiler.WindowsInstaller/Product.wxs#L122).

> So I guess a section in the agent.yaml that can list the apps to be profiled might work?

Exactly. We plan to add global- and application-level configuration files which would allow you to enable or disable the profiler early in the `ICorProfilerCallback::Initialize` callback.

**Comment by rlaveycal** [comment]
😀

**Comment by lucaspimentel** [comment]
Environment variables `COR_ENABLE_PROFILING` was added to the documentation, and there are reasons (explained above) why the msi installer does not add it globally. Closing this issue.
