### ISSUE TITLE
How to create a root scope with v2 API

### ISSUE THREAD

**Issue by tylerohlsen** [DataDog/dd-trace-dotnet#2267]
I'm not finding a way for my code to create a new root scope with the v2 API.  With the v1 API, I was able to pass in `true` to the `ignoreActiveScope` parameter of `Tracer.Instance.StartActive`.  That's no longer an option and not exposed on `SpanCreationSettings`.  

If I leave `Parent` as _null_ on `SpanCreationSettings`, then the default behavior is to inherit.  And if I try to set `Parent` to a new _empty_ `SpanContext`, I cannot because the only public constructor requires I pass a `ulong spanId` (not nullable) and I do not have access to the _internal_ `SpanIdGenerator`.

So am I missing something?  Is there another way to create a root span?

**Comment by lucaspimentel** [comment]
Hey, Tyler. We removed this feature in 2.0 intentionally because it is tricky to support and rarely used. Can you tell us more about your use case and what you are trying to do by creating new root scopes manually? We may be able to suggest a different solution. Or, if needed, we can look into bringing this feature back to the tracer. Thanks!

**Comment by tylerohlsen** [comment]
We currently have downstream processes that continue the work of an activity that we want correlated to the upstream process.  Those downstream processes are triggered via RabbitMQ and Redis Pub/Sub.  We currently have a custom method that puts the full trace id in the RabbitMQ message correlation id header and on the subscriber side we start a new scope with that correlation id header value as an explicitly created parent (root) scope.  And similarly with Redis Pub/Sub, we include the full trace id in the published message payload.

Also, out-of-the-box a trace is inherited for the entire lifetime of a user's SignalR connection.  We currently create a new root scope on every SignalR Hub method call so we do not have a trace that lasts for a very long time (in extreme cases, hours).

**Comment by lucaspimentel** [comment]
Thanks, Tyler. I see two use cases here: propagating a span context to another service (your RabbitMQ/Redis example using message headers), and legitimately stopping a new span from becoming the child of the currently active span (SignalR). Both involve specifying what you want a span's parent to be when creating a new span.

----

For distributed trace propagation (your RabbitMQ/Redis example), you want to create a new span with a given trace id and parent span id that you receive from an upstream service. For this, you create a `ISpanContext` that represents the parent span, and you don't need `ignoreActiveScope`. In tracer 1.x, the value of `ignoreActiveScope` was only relevant if `parent` was `null`, otherwise it is ignored. The syntax is different in 2.x. but you can still pass a parent span context when creating a span:

```csharp
// assuming you get traceId and spanId from the incoming message headers,
// this SpanContext represents the remote span which published the message
ulong traceId = ...;
ulong spanId = ...;
var settings = new SpanCreationSettings { Parent = new SpanContext(traceId, spanId) };
var scope = Tracer.Instance.StartActive("span-name", settings );
```

----

For the SignalR scenario, you want to create a span that has _no_ parent, so it becomes the root of a new trace. In this case, passing `parent = null` is not enough: if you do, we fall back to using the currently active span as the parent. This is the case in both 1.x and 2.x. With `ignoreActiveScope`, you had a change to say, "I _really_ don't want a parent", but that parameter is no longer available. There is one workaround you can use for now and we will look into improving this API:

```csharp
// When traceId or spanId are null or zero, we treat this as "no parent",
// so we generate new random values. But since you're not passing null,
// we don't fall back to using the currently active as the parent.
var settings = new SpanCreationSettings { Parent = new SpanContext(0, 0) };
var scope = Tracer.Instance.StartActive("span-name", settings );
```

If you will do this often, consider caching the "empty" span context instance so you can reuse it as your "empty parent".

**Comment by tylerohlsen** [comment]
Are you sure `new SpanContext(0, 0)` is correct?  The first parameter is nullable and only when it is null does it generate a new id. And the second parameter is not nullable and [blindly assigns the value](https://github.com/DataDog/dd-trace-dotnet/blob/v2.0.1/tracer/src/Datadog.Trace/SpanContext.cs#L31).  Is there something downstream that handles the zero values that I’m not seeing?

**Comment by lucaspimentel** [comment]
Yes, this `SpanContext` will have `0` as both its traceId and spanId. If you use this as the _parent_ for a new span, the new span will use a different `SpanContext` constructor to create its own context:
https://github.com/DataDog/dd-trace-dotnet/blob/caaf1d55159c0513c4ea2f9aa1e0e17a4f77a22c/tracer/src/Datadog.Trace/SpanContext.cs#L69-L72

This constructor in turn calls this other one:

https://github.com/DataDog/dd-trace-dotnet/blob/caaf1d55159c0513c4ea2f9aa1e0e17a4f77a22c/tracer/src/Datadog.Trace/SpanContext.cs#L81-L85

You can see both `TraceId` and `SpanId` for the child's `SpanContext` are set to `SpanIdGenerator.ThreadInstance.CreateNew()`, effectively becoming the root span of a new trace. 

There's a small but inconsequential detail: when serializing this root span, we will encode `ParentId` as `0` instead of skipping it, but `ParentId=0` is acceptable to the rest of our pipeline (Agent, backend, etc) and is known to mean "no parent".

https://github.com/DataDog/dd-trace-dotnet/blob/caaf1d55159c0513c4ea2f9aa1e0e17a4f77a22c/tracer/src/Datadog.Trace/Agent/MessagePack/SpanMessagePackFormatter.cs#L78-L82

----

We are considering adding a static `SpanContext.Empty` ([see a draft PR](https://github.com/DataDog/dd-trace-dotnet/pull/2309/files)) to make this a little easier and more explicit. The new usage would look something like:

```csharp
// Don't inherit the active span as the parent.
var startNewTrace = new SpanCreationSettings { Parent = SpanContext.Empty };

// This scope is now the root of a new trace.
// NOTE: It is also the active span in `Tracer.Instance.ActiveScope`. 
var scope = Tracer.Instance.StartActive("span-name", startNewTrace);
```

**Comment by tylerohlsen** [comment]
Great, that should work for us then.  

But out of curiosity, why not make `spanId` nullable just like `traceId` on the public constructor?  Passing in `0` is not very discoverable and undocumented.

https://github.com/DataDog/dd-trace-dotnet/blob/caaf1d55159c0513c4ea2f9aa1e0e17a4f77a22c/tracer/src/Datadog.Trace/SpanContext.cs#L35

**Comment by lucaspimentel** [comment]
Tyler, `SpanContext.None` was added in [release 2.2.0](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v2.2.0) today so I will close this issue.

Thanks again for your feedback!
