### ISSUE TITLE
Exception when instrumenting application with multiple AppDomains

### ISSUE THREAD

**Issue by doronneumann** [DataDog/dd-trace-dotnet#238]
**Describe the bug**
When creating an AppDomain in a C# application, the following exception is thrown:
System.Runtime.Serialization.SerializationException: Type 'Datadog.Trace.Scope' in assembly 'Datadog.Trace, Version=0.5.1.0, Culture=neutral, PublicKeyToken=def86d061d0d2eeb' is not marked as serializable.

**To Reproduce**
1. Instrument an application which uses the AppDomain.CreateDomain(...)
2.Run it
3. Get the exception

**Expected behavior**
No exception should be thrown.

**Screenshots**

**Runtime environment (please complete the following information):**
- Automatic with MSI install
- Tracer version: 0.5.2-beta
- OS: Windows Server 2016
- CLR: .NET Framework 4.6.2

**Additional context**

**Comment by gshackles** [comment]
We're also seeing this error happening in code that makes some calls via .NET Remoting

**Comment by urtho** [comment]
Same here. I have this in multiple apps.
My apps were also failing under Azure Insights and new DLL solved this.
https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/613 

Created DDog support ticket for this on November 21.

**Comment by boskya** [comment]
We also see this issue in our application with 0.7-beta and in integration with another third party library - TuesPechkin which is also creating appDomains. Looking forward to a fix.

**Comment by gshackles** [comment]
@doronneumann I can attest to that not being the case, since I was chatting with folks there about it as recently as yesterday and it was being looked into 😄

**Comment by doronneumann** [comment]
I reported it 2 months ago, so I am less optimistic than you are.

**Comment by lucaspimentel** [comment]
Hey, @doronneumann. My apologies for the lack of communication regarding this issue. It is causing customer applications to crash so it is definitely a **high priority** for us. Like @gshackles said, we are actively working on resolving this.

There are actually several different things reported here that all end up trying to serialize a `Scope`. Unfortunately, the solution is not as simple as tacking a `[Serialiazable]` attribute on the `Scope` class. We are working on solutions for both AppDomains and .NET Remoting.

If your app creates multiple AppDomains, a work-around you can try right now is to remove `Datadog.Trace.ClrProfiler.Managed` from the GAC after running the MSI installer and add the [NuGet package](https://www.nuget.org/packages/Datadog.Trace.ClrProfiler.Managed) to your app instead. If your app targets `net461` or above, VS will pick the assembly that [uses `AsyncLocal` instead of `CallContext`](https://github.com/DataDog/dd-trace-dotnet/blob/095ea9ac912bae7265dd341bdb38196430aa5ea9/src/Datadog.Trace/AsyncLocalCompat.cs#L33) and the serialization error should go away.

**Comment by lucaspimentel** [comment]
@boskya: thanks for testing this! That was my mistake. The offending code is in `Datadog.Trace`, not `Datadog.Trace.ClrProfiler.Managed`. I'll fix my comment above. Can you try again removing both from the GAC? Note that the `Datadog.Trace.ClrProfiler.Managed` NuGet package has a dependency on the `Datadog.Trace` package, so your app will pull them both. However, if there is a match found in the GAC, your application will use that one instead.

**Comment by lucaspimentel** [comment]
@doronneumann: Can you provide a minimal project with code that reproduces this issue? We want to make sure your use case is covered by the solution we are working on.

**Comment by boskya** [comment]
@lucaspimentel the workaround did work. Let me see If I can spin up a minimal project for you.

**Comment by lucaspimentel** [comment]
Bugfix [release 0.7.1](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v0.7.1-beta) should resolve the `SerializationException` when creating a new `AppDomain`.
