### ISSUE TITLE
How to get a method signature

### ISSUE THREAD

**Issue by wang9563** [DataDog/dd-trace-dotnet#241]
I see `internal SqlDataReader ExecuteReader(CommandBehavior behavior, string method)` signature is `20 02 0C 52 08 0B 52 5B 0E` ，But I use `CFF Explorer` find signature is `20 02 12 87 00 11 82 54 0E` , how to convert ?

I want to write some code to wapper [MySqlConnector](https://github.com/mysql-net/MySqlConnector) by `Datadog.Trace.ClrProfiler.Native.dll` , what way can i get any `method signature` in other assembly ? 

thanks.

**Comment by lucaspimentel** [comment]
Hello, @wang9563. The method signature in `method_replacements.target.signature` is optional and only needed to distinguish between multiple overloads. The only integration that currently uses this is the SQL Server integration, because we instrument two overloads of `System.Data.SqlClient.SqlCommand.ExecuteReader()`:

- [`ExecuteReader(CommandBehavior, string)`](https://github.com/DataDog/dd-trace-dotnet/blob/develop/integrations.json#L165)
- [`ExecuteReader(CommandBehavior)`](https://github.com/DataDog/dd-trace-dotnet/blob/develop/integrations.json#L180)

For now, we only compare the calling convention (first byte) and the number of method parameters (second byte) in the signature to determine if a method call is a match (see [this code](https://github.com/DataDog/dd-trace-dotnet/blob/9c2a5e997baaebf2fb04bac2967d488af94a1012/src/Datadog.Trace.ClrProfiler.Native/cor_profiler.cpp#L298-L312)). The rest of the signature is ignored because metadata tokens are not consistent between library versions.

In the future, we plan to replace the signature bytes into something that includes the type names instead. For example:

```
"target": {
    "returnType": ["System.Data.SqlClient.SqlDataReader"],
    "parameterTypes": ["System.Data.CommandBehavior", "System.String"]
}
```

**Comment by wang9563** [comment]
Thanks. This is great.
Also, This feature will be better. I will mind this.
