### ISSUE TITLE
Can't get SpanContext from Span (for use in childOf of Tracer.{StartActive,StartSpan})

### ISSUE THREAD

**Issue by toqueteos** [DataDog/dd-trace-dotnet#243]
**Are you requesting automatic instrumentation for a framework or library?**
No

**Is your feature request related to a problem?**
I'm using manual instrumentation and I cannot get a `SpanContext` from a `Span` (using `v0.6.0-beta` and `dotnet --version = 2.2.101`).

**Describe the solution you'd like**
It seems `Span` does have an underlying `SpanContext` but it's not exposed (`internal` visibility), exposing this would help me to create child traces which right now I can't.

**Describe alternatives you've considered**
Either changing the signature of `Tracer.StartActive` and `Tracer.StartSpan` to take a `Span` instead of a `SpanContext` or adding a new override.

**Additional context**
N/A

**Comment by lucaspimentel** [comment]
Thanks for the feedback, @toqueteos. We will look into improving usability in this area soon. In the meantime, note that passing a null `SpanContext` to `Tracer.StartActive` creates a span that is a child of the currently active span. `null` is the default value for that optional parameter, so in most cases you can just call:
```csharp
var scope = Tracer.StartActive(operationName);
```

**Comment by toqueteos** [comment]
Good to know, thank you very much Lucas!

**Comment by stevenhaohuitan** [comment]
@lucaspimentel any update on this?

**Comment by stevenhaohuitan** [comment]
@lucaspimentel For the solution, is it possible to have more than one active spans at a given time? If you have more than one active spans, which parent span are you going to assign to the child span that you're creating?

**Comment by HenryYuST** [comment]
@lucaspimentel 

Correct me if I'm wrong but I think your suggestion does not work when we are tracing across 2 independent services. We would like to be able to see spans from different services in the same flame graph. So we are trying to create child spans using a span from a different service as the parent span.
We found out in order to be able to trace a message between two independent services, we need to pass SpanContext to the receiver so that the receiver can create a child span using the context from the sender.
After making the changes below to Span.cs, we were able to make it work. Would you consider making the following changes at
https://github.com/DataDog/dd-trace-dotnet/blob/de87820fe8a0e7e86643c087b810757c0fa2ee39/src/Datadog.Trace/Span.cs#L70
to
```
        /// <summary>
        /// Gets the span context identifier.
        /// </summary>
        public SpanContext Context { get; }
```
I tried to create a pull request but did not have the permission to do so.
Thank you.

**Comment by nle-solutiontek** [comment]
@lucaspimentel is it possible to get this implemented? Changing from internal to public seems to work just fine

**Comment by lucaspimentel** [comment]
@HenryYuST: You need to fork the repo to create a PR. See the [GitHub documentation on this topic](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork). I recommend talking to the dev team to plan new features before doing any work, though.

Back to the original issue, the Tracer library treats propagated contexts differently that local ones. The best way to propagate a span's context across services (aka distributed tracing) it to pass the trace id and span id (which are available on `Span`) to the remote process, and create a new `SpanContext` there.
```csharp
// locally
var traceId = span.TraceId;
var spanId = span.SpanId;

// pass those values to the remote process (e.g. in http headers)
// and create a new "propagated" context there
var propagatedContext = new SpanContext(traceId, spanId);
```



@nle-solutiontek: We need to consider the implications of making this property `public`. Once it's done, it's part of the public API and harder to change without breaking changes. If we do this, we probably want to expose an `ISpanContext` instead of the concrete `SpanContext` type, for example.

**Comment by macrogreg** [comment]
Hi folks,

There were no updates on this issue for a while. I will go ahead and close it, but please feel free to reopen if you feel this is still actionable.

In this context, please note that we are currently working on support for .NET native Activity APIs, which should certainly support this scenario.
