### ISSUE TITLE
about some suggestion

### ISSUE THREAD

**Issue by caozhiyuan** [DataDog/dd-trace-dotnet#244]
1、.net framefork GAC and .net core DOTNET_ADDITIONAL_DEPS env can make none ref nuget.
2、i think native c++ profiler replace methodcall il may be not a good way, we can just change profiler method il . ( consider some async method, we can use profiler api define method (copy profiler method and rename )  and change profiler method il to call managed profiler dll method , and use managed code call profiler api define method .)

**Comment by caozhiyuan** [comment]
here is code sample (https://github.com/caozhiyuan/clr-samples/blob/master/ProfilingAPI/ClrProfiler/CorProfiler.cpp) , but i think add try catch finnally is a best way.)

**Comment by caozhiyuan** [comment]
i finished add try catch finnally , so we can use ioc in WrapperService

**Comment by caozhiyuan** [comment]
@lucaspimentel any idea?

**Comment by lucaspimentel** [comment]
Thanks for the feedback, @caozhiyuan. We considered this approach (modifying the instrumented method), but decided to go with replacing the method calls instead for version 1.0 because it seems easier to implement at the time. There's a possibility we might go with a different approach in the future (2.0?), but it depends on how things go and lessons learned. However, it's not going to happen short term.
