### ISSUE TITLE
Reliably deal with Agent's payload size limitation

### ISSUE THREAD

**Issue by Gerarddp** [DataDog/dd-trace-dotnet#259]
**Describe the bug**
Log message
An error occurred while sending traces to the agent at http://localhost:8126/v0.3/traces

ERROR MESSAGE
Response status code does not indicate success: 413 (Request Entity Too Large).

ERROR STACK
System.Net.Http.HttpRequestException: Response status code does not indicate success: 413 (Request Entity Too Large).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Datadog.Trace.Agent.Api.<SendAsync>d__8`1.MoveNext()

**To Reproduce**
1. Install the automatic instrumentation
2. Wait 5min
3. Errors start appearing

**Expected behavior**
No errors 😄 

**Runtime environment (please complete the following information):**
- Instrumentation mode: automatic 
- Tracer version: both 0.7.0 and 0.7.1 (installed on top of 0.7.0 and I don't know how to check which version is running)
- OS: Windows Server 2016 Datacenter
- CLR: .NET Framework 4.6.1

**Additional context**
Not all messages are failing, most are working correctly.

**Comment by jhaygood86** [comment]
The applications I work on get this periodically. We aren't using the automatic Instrumentation. Stack trace is the same.

**Comment by johnnychu** [comment]
The applications our team builds get this error frequently. Is there anyway we can get this error fixed?

**Comment by mikekatica** [comment]
I think this issue is related to the agent as much as tracing. It happened to telegraf datadog output as well. I think we should open an issue in the agent repo as well.

**Comment by lucaspimentel** [comment]
The Agent endpoint currently has a hard [payload limit of 10MB](https://github.com/DataDog/datadog-agent/blob/bf4a73b4e1cbc502693fdf6794791e43f8355ba5/pkg/trace/api/api.go#L31). A 10MB trace serialized with MessagePack it a very, very big. If any of these traces make it through to the Datadog server, do you know how many spans they contain? For 10M, I would expect many thousands of spans or tons of metadata (tags).

Anyway, since the Agent is not going to accept these huge traces, there are two things we can do from the Tracer side:
- easy/fast: we could [change the log level](https://github.com/DataDog/dd-trace-dotnet/blob/ec8d85a2e76516a5ba1190d073406292e5419f43/src/Datadog.Trace/Agent/Api.cs#L76) of these specific `413 (Request Entity Too Large)` errors so they can be ignored via log configuration while still logging other (possibly more important) messages
- larger long-term project: try to determine the size of the payload before sending it, and splitting big payloads into multiple HTTP requests to the Agent. This would probably require serializing the trace multiple times as more and more spans are added to it, which would increase the Tracer's CPU and memory usage.

**Comment by realnickivanov** [comment]
Easy/fast solution is not what me or my company would like to see. We can ignore this error without a Tracer's help. Instead, we would like to see a solution, that already works on [ruby](https://github.com/DataDog/dd-trace-rb/issues/220), or ready for a release for [python](https://github.com/DataDog/dd-trace-py/issues/460).

Can we tell that those 10MB (or more) contains useful information? If yes, it shouldn't be ignored. If not, it would be great if you could help us to make it smaller by keeping only what needs to be kept.

**Comment by yaselc** [comment]
We are receiving many events of this type in our Sentry project. The truth is that I do not need the agent's endpoint to accept this payload, if the limit is 10MB, it's fine by me, but instead of seeing an exception, I'd love to see an alert on the Datadog dashboard indicating the specific operation that exceeds the payload limit. Some useful information could be drawn from the entire payload to at least inform this.

**Comment by lucaspimentel** [comment]
@realnickivanov and @yaselc: Thanks for the feedback! We will take this into consideration.

**Comment by realnickivanov** [comment]
Any update here? I believe we keep losing some log information because of this bug, for example large error messages cannot be logged. Instead we see this "An error occurred while sending traces to the agent" error.

**Comment by AndiRudi** [comment]
Any updates on this? We have 7.4k Messages like this in Airbrake....

**Comment by macrogreg** [comment]
Internal issue tracker:
https://datadoghq.atlassian.net/browse/DOTNET-63

**Comment by macrogreg** [comment]
A prototype below uses timing (like now) and also the number of traces in the buffer to initiate sending:

https://github.com/DataDog/dd-trace-dotnet/tree/gregp/hack-a-dog-202007-diagnosticsource-activity/src/Datadog.Trace.ClrProfiler.Managed/ActivityBasedTracing

**Comment by macrogreg** [comment]
Note the additional submission for this issue (with a different symptom): https://github.com/DataDog/dd-trace-dotnet/issues/517

**Comment by rakker91** [comment]
Note that #517 is probably a side effect of the agent payload limit: `AgentWriter` is limiting the number of traces to 1000 per second to avoid the payload limit.  

Specifically, `AgentWriter` has an `AgentWriterBuffer` that's limited to 1000 items and is flushed every 1 second (lines 12 and 116 in `AgentWriter`).  If that limit is exceeded, `AgentWriterBuffer` randomly replaces traces with the new trace (line 31 of `AgentWriterBuffer`).

Once the payload size limit is addressed, AgentWriter will need to be updated to remove the 1000 per second limit or deal with it another way.  I know DataDog would love for us to pay for > 1000 per second of analyzed spans . . . :)  We can generate up to 10,000 per second.

**Comment by macrogreg** [comment]
Seems this has been reported again here: https://github.com/DataDog/dd-trace-dotnet/issues/1002

**Comment by lippinio** [comment]
We are faceing a similar Issue with Backgroundjobs that produce a lot of spans (> 10k). And from the Datadog API is 413 returned. We saw in other clients are kind of batching in place. Is anything like this planed for the dotnet agent too?

**Comment by colin-higgins** [comment]
This is resolved as of https://github.com/DataDog/dd-trace-dotnet/pull/1151
Please open a new issue if you have any problems or feedback.
Thank you.
