### ISSUE TITLE
DataDog.Trace.OpenTracing should support `ISpan.Log` or no-op

### ISSUE THREAD

**Issue by Aaronontheweb** [DataDog/dd-trace-dotnet#269]
When using a framework instrumented with `OpenTracing`, any time an `ISpan.Log` call is made it produces a `ISpan.Log is not implemented by Datadog.Trace` DEBUG message.

This is due to the fact that, as the error message describes, this feature is simply not implemented by DataDog at this time:

https://github.com/DataDog/dd-trace-dotnet/blob/3e527837f4a84fbbfd5d2b8257223e1961cb1b14/src/Datadog.Trace.OpenTracing/OpenTracingSpan.cs#L40-L44

In system where lots of pieces of data are being logged, this makes the `Debug` log quite noisy but more importantly - `ISpan.Log` is actually a rather important part of the OpenTracing ecosystem as a whole, as that's often how framework specific logs and critical events are recorded in the context of the trace.

**Describe the solution you'd like**
Ideally DataDog should implement the `ISpan.Log` interface and have it propagate log data to individually traced operations.

If that isn't feasible for whatever reason, don't log anything or only log the first N occurrences of the issue so the same message isn't logged over and over again by the frameworks that are calling the `ISpan.Log` interface.

**Describe alternatives you've considered**
Wrapping the `Datadog.Trace.OpenTracing` in our own NuGet package in order to elide the calls to `Datadog.Trace.OpenTracing.OpentracingSpan.Log`.

**Comment by gshackles** [comment]
Just wanted to add in my support for this - if the DD tracer can't support the logging parts of the interface here, I think it would definitely be better to either just drop those silently and call it a documented limitation, or just log it once and then suppress future ones. I'd also happily submit the PR to remove those log lines if there's agreement 😄

**Comment by lucaspimentel** [comment]
Thanks for the feedback! Yes, a PR would be much appreciated. We have plans to add log throttling/rate-limiting soon, so if there's an easy way[1] to log the warning just once, let's do that, otherwise, you can remove it entirely. We can add them back later when real throttling is implemented.

[1] A static boolean field might be enough. We probably don't need locking around it because reading/writing it is atomic (i.e. we'll never read corrupted data), and at worse, a race condition will just write the log entry more that once. It's still much better than what happens now.

**Comment by lucaspimentel** [comment]
Thanks for the PR. The code changes were included in [release 0.8](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v0.8.0-beta). Closing this issue.
