### ISSUE TITLE
Environment variables missing?

### ISSUE THREAD

**Issue by jyjohnson** [DataDog/dd-trace-dotnet#317]
On Windows Server, .net web apps running under IIS. I have installed APM via MSI installer. I see the registry keys (System\CurrentControlSet\Services\W3SVC\Environment and System\CurrentControlSet\Services\WAS\Environment). However when running SET at the command prompt the only DD related variable is DD_INTEGRATIONS (which is pointing to a non-existing file). Do I need to add the others or is the registry value sufficient? Note: in our case we want to automatically instrument all IIS web apps.

**Comment by lucaspimentel** [comment]
Hi, @jyjohnson.

> when running SET at the command prompt the only DD related variable is DD_INTEGRATIONS

Environment variables set in `System\CurrentControlSet\Services\<name>\Environment` are not global and apply only to that Windows Service. This is why they are not defined in a command prompt. If you were to set the profiler variables globally, the profiler would attach to _all_ .NET processes, which is usually not what you want. See ["Setting Up a Profiling Environment - Environment Variable Scope"](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/profiling/setting-up-a-profiling-environment#environment-variable-scope) for more details.

The `DD_INTEGRATIONS` variable is fine to define globally since that variable by itself will not enable the profiler and it is only accessed if the profiler is loaded into a process. Defining it globally also reduces the number of variable that a user needs to set manually if their application is not running in IIS.

> DD_INTEGRATIONS ... is pointing to a non-existing file

Can you expand on this? Where is it pointing to?

> we want to automatically instrument all IIS web apps.

This is the main use case that we target with the msi installer. Just run the msi and restart IIS. No additional steps are needed!

**Comment by jyjohnson** [comment]
env variable DD_INTEGRATIONS=c:\Program Files\Datadog\.NET Tracer\integrations.json

The "\.NET Tracer" folder is empty (in all of ec2/on-prem vms that have the APM installed) -- there is no integrations.json file.

**Comment by lucaspimentel** [comment]
Closing this issue since it seems like you found the file.

Just to be clear about the different paths, the msi installer installs files (including `integrations.json`) into `%PROGRAMFILES%\Datadog\.NET Tracer` and into .NET's Global Assembly Cache (GAC). This is the default path but can be changed by the user during installation.

The tracer uses `%PROGRAMDATA%\Datadog .NET Tracer` for files created or modified at run time, like the profiler log file, `dotnet-profiler.log`.
