### ISSUE TITLE
-http-client appended to ServiceName in APM

### ISSUE THREAD

**Issue by markhoratiowalmsley** [DataDog/dd-trace-dotnet#3332]
**Describe the bug**
We have additional services being sent to datadog using the apm library. The text "-http-client" seems to get appended to the end of each service by default. We are trying to switch to used unified tagging for our services and can't get this last remaining group of services to be unified. We are using configuration in code using the following:

`

            var settings = TracerSettings.FromDefaultSources();

            var dataDogConfiguration = new DataDogConfiguration();
            context.Configuration.GetSection(dataDogConfigurationSectionName).Bind(dataDogConfiguration);
            settings.Environment = dataDogConfiguration.Environment;
            settings.ServiceName = dataDogConfiguration.ServiceName;
            settings.ServiceVersion = Assembly.GetExecutingAssembly().GetName().Version?.ToString() ?? "1.0.0";
            settings.Exporter.AgentUri = dataDogConfiguration.AgentUri;
            settings.StartupDiagnosticLogEnabled = dataDogConfiguration.EnableTracing;
            settings.LogsInjectionEnabled = dataDogConfiguration.EnableTracing;
            settings.TraceEnabled = dataDogConfiguration.EnableTracing;
            settings.TracerMetricsEnabled = dataDogConfiguration.EnableTracing;

`

**To Reproduce**
1. Import Data.Monitoring.Distribution 2.6.0-beta01 / Datadog.Trace 2.10 / Serilog.Sinks.DataDog 0.3.6 and configure as above
2. See the following in apm logs

![image](https://user-images.githubusercontent.com/30492429/194903857-5b7e81b7-881f-4731-af7c-d8828d8f81a8.png)

**Expected behavior**
The configured ServiceName to appear within our logs, without -http-client appended.

**Runtime environment (please complete the following information):**
- Above packages using nuget. 
- .net 6
- Linux image deployed to AppService in azure

**Additional context**
This codebase is 'legacy' so we could very well be doing something stupid on our end, it doesn't look as if there is anything obvious that would suggest it is.

**Comment by andrewlock** [comment]
Hi @markhoratiowalmsley, thanks for reaching out. The `-http-client` suffix is currently the expected behaviour. There are ongoing internal discussions around the best approach here, but there are good reasons for having the suffix. For example, by having a separate "service" for your remote operation (httpclient/database etc), you automatically get metrics and details about the remote calls, which you would lose otherwise. 

It's possible (but not recommended) to remove the extra `http-client` suffix using the `DD_TRACE_SERVICE_MAPPING` configuration, as described in [the documentation](https://docs.datadoghq.com/tracing/trace_collection/library_config/dotnet-core?tab=environmentvariables). In your example, you would use the value `http-client:document-api`.

I hope that helps and makes sense!

**Comment by lucaspimentel** [comment]
@markhoratiowalmsley, I hope Andrew's suggestion above solved your issue. Feel free to re-open this issue if you have more questions related to this.

**Comment by markhoratiowalmsley** [comment]
Sorry I completely forgot to reply to this. We have gone with keeping http-client if that is the suggested usage!

**Comment by gaberogan** [comment]
Ran into this and found out it was because the dd-trace package was on an old version 0.33.x. Upgraded to 3.x and it's fixed.

**Comment by bouwkast** [comment]
Hey @gaberogan!

Just out of curiosity, what package did you upgrade from? I was just poking around our versions of various NuGets and none seem to have a `0.33.*`. Maybe an early beta of https://www.nuget.org/packages/Datadog.Trace? If so that is quite the upgrade to our new major version. If so, hopefully the upgrade process went well🙂
