### ISSUE TITLE
Instrumentation for .NET Windows Service

### ISSUE THREAD

**Issue by voidmonk** [DataDog/dd-trace-dotnet#343]
Hi, I couldn't find this information in your docs, so I thought I'd ask here.

We have a .NET Windows Service (based on .NET Framework 4.7.2, built with TopShelf library, running under Windows Server 2016). The Windows Service performs background processing, which in-turn make database calls, web requests etc.

Is it possible to use the Datadog .NET tracer agent to automatically instrument a .NET Windows Service, so that its methods, internal calls and uncaught exceptions can be traced? If possible, then how should I go about it, and what are the steps involved?

**Comment by lucaspimentel** [comment]
You can instrument any .NET process by setting up the following [environment variables](https://docs.datadoghq.com/tracing/setup/dotnet/?tab=netframeworkonwindows#required-environment-variables):
```
COR_ENABLE_PROFILING=1
COR_PROFILER={846F5F1C-F9AE-4B07-969E-05C26BC060D8}
```

We do not recommend setting them globally, since that will cause the profiler to attach to all .NET processes on the host. You can add env vars to a specific Windows Service in the Windows Registry at the following location:
```
HKLM\System\CurrentControlSet\Services\{service name}\Environment
```
where "service name" is the name of the Windows Service you want to instrument. For example, [our MSI installer adds these values](https://github.com/DataDog/dd-trace-dotnet/blob/12926d187c16467d5c60e36d28b9c3fa6398c28a/deploy/Datadog.Trace.ClrProfiler.WindowsInstaller/Product.wxs#L148-L150) in `HKLM\System\CurrentControlSet\Services\W3SVC\Environment`, since `W3SVC` is the service that runs IIS.

Hope this helps!
