### ISSUE TITLE
Make SamplingPriority on SpanContext public

### ISSUE THREAD

**Issue by andreas-soroko** [DataDog/dd-trace-dotnet#345]
**Is your feature request related to a problem? Please describe.**
https://github.com/DataDog/dd-trace-dotnet/blob/12926d187c16467d5c60e36d28b9c3fa6398c28a/src/Datadog.Trace/SpanContext.cs#L91

i trying to forward the informations to the next service (over kafka) but the property "SamplingPriority" on the SpanContext is internal, is there any reason for that ? 
it is possible to change that ?

**Describe the solution you'd like**
public instead of internal.

**Comment by lucaspimentel** [comment]
Thanks for the feedback. I agree that we should provide this value for users who are implementing distributed tracing themselves. We will provide a way to access a trace's sampling priority soon. 

It will probably look something like this since the value can come from two different sources depending on how the `SpanContext` was created:
```csharp
public SamplingPriority? SamplingPriority => _samplingPriority ?? TraceContext?.SamplingPriority;
```

**Comment by jinhong-** [comment]
I currently have similar needs too.. Any ETA on this?

**Comment by macrogreg** [comment]
This has been stale for a long time now. Datadog has many new features around sampling since then, so I am guessing that this is no longer current. I will close this issue for now, but please feel free to reopen if I guessed wrong. :)

Please, also note that we are currently looking into supporting .NET native Activity APIs to describe spans. In that context, you should be able to use the respective mechanism to influence the sampling behavior.
