### ISSUE TITLE
set -euxo pipefail: exit code: 2 when using Datadog.Trace.Bundle in Ubunutu docker image

### ISSUE THREAD

**Issue by ryan-unleashed** [DataDog/dd-trace-dotnet#3516]
**Describe the bug**
When using `Datadog.Trace.Bundle` package with the `mcr.microsoft.com/dotnet/aspnet:6.0` attempting to run createLogPath.sh exits with error code 2. Switching the base image to `mcr.microsoft.com/dotnet/aspnet:6.0.10-alpine3.16-amd64` allows the script to succeed.

**To Reproduce**
1. Create a simple console hello world app with .NET 6
2. Add the Datadog.Trace.Bundle package
3. Create a simple docker file to build an image from the console app using `mcr.microsoft.com/dotnet/sdk:6.0` and `mcr.microsoft.com/dotnet/aspnet:6.0`
4. Build the docker image using `docker build .`
5. Error `set -euxo pipefail: exit code: 2` is thrown
6. Change to an alpine image and the script will succeed
7. Removing the -o option in the first line of the script allows the script to succeed as well

**Expected behavior**
I expected the script to create the log directories required

**Runtime environment (please complete the following information):**
- Instrumentation mode: Automatic and manual instrumentation using the new `Datadog.Trace.Bundle` package
- Tracer version: 2.19.0
- OS: I think Ubuntu when building in docker using `mcr.microsoft.com/dotnet/sdk:6.0`
- CLR: NET 6.0

**Additional context**
- Possibly related to this issue? https://askubuntu.com/a/886540
- Repro project attached [datadog-trace-bundle-repro.zip](https://github.com/DataDog/dd-trace-dotnet/files/10099922/datadog-trace-bundle-repro.zip)

**Comment by andrewlock** [comment]
Hi @ryan-unleashed,

It looks like the issue here is the way you're trying to run `createLogPath.sh`. In your dockerfile, you're doing 

```dockerfile
RUN sh /app/datadog/createLogPath.sh
```

which uses the default shell to run `createLogPath.sh`. As you highlighted in [the linked post](https://askubuntu.com/a/886540), this isn't necessarily `bash`, which causes the failure.

Instead, you should do:

```dockerfile
RUN chmod +x /app/datadog/createLogPath.sh && /app/datadog/createLogPath.sh
```

This makes the script executable and runs it. Running scripts like this uses the shebang in the script (`#!/bin/bash`) to choose the correct shell (`bash`), which solves the issue.

Hope that helps!

**Comment by ryan-unleashed** [comment]
Yep that seems to sort it out, thanks! 

I reckon it's probably a good idea to update the docs to mention this alternative. I was following instructions here for the nuget package: https://docs.datadoghq.com/profiler/enabling/dotnet/?tab=nuget#installation
