### ISSUE TITLE
Allow Advanced Filtering rules in the Azure Function App Extension

### ISSUE THREAD

**Issue by m-scipione** [DataDog/dd-trace-dotnet#3639]
I have an Azure Function App written in .NET with ILogger direct submission enabled... I have the latest version of the ".NET Datadog Extension" installed, 2.21.0. 

The traces/logging for the legitimate invocations work great, however, every few seconds the Azure platform performs a few various "checks" (e.g. `/admin/host/status`, `/admin/host/ping`, etc.):
  
![image](https://user-images.githubusercontent.com/25613680/211453080-b477bdc6-fb6a-4acf-8259-bd777a70e2cf.png)

This generates an excessive amount of unnecessary data. I'd like to be able to specify some advanced filtering rules in the Function App's configuration to be able exclude traces from a specified endpoint from being sent to Datadog.

Here's an example (which would exclude the `/admin/host/ping` from sending any trace data to Datadog):
![image](https://user-images.githubusercontent.com/25613680/211454128-c2cda8ee-5f90-415e-94d7-52f655eea0b1.png)

**Comment by andrewlock** [comment]
Hi @m-scipione,

The approach you could take here depends on whether it's _logs_ you want to filter out or _traces_ (the screenshot above shows traces). 

For filtering _log_ messages, we recently (`v2.20.0`) added support for filtering `ILogger` logs when using direct log submissions as described in this PR: https://github.com/DataDog/dd-trace-dotnet/pull/3487. You can add the config to your appSettings.json file, or as environment variables just as you would for other ASP.NET Core log filtering rules.

For traces, you should be able to use [the `DD_APM_IGNORE_RESOURCES` setting](https://docs.datadoghq.com/tracing/guide/ignoring_apm_resources/?tab=dockercompose#ignoring-based-on-resources) to ignore the root spans with specified resource names. For example I think the following should filter out all resources shown above:

```bash
DD_APM_IGNORE_RESOURCES="GET /admin/host/*, GET /admin/functions/function1/status"
```

Hopefully these options solve your issue, but let us know if you continue to have difficulty.

Regarding the filtering of traces, I think there's a strong argument to be made that we should _never_ trace these requests in functions apps, as I can't imagine anyone finds them useful. At the very least we could avoid tracing them by default, and allow users to opt-in to tracing.

**Comment by m-scipione** [comment]
@andrewlock thanks for the quick and very helpful reply! Thanks for clarifying between traces and logs. I do agree with your take that disabling the "administrative" traces by default would be a great idea, then the folks who may want to use them can pass in a "true" parameter to the settings and have them available. 

To answer your question, my Function App is set to be triggered by HTTP request (happy to provide more details if helpful). I first noticed this issue because I know I wasn't triggering the function (and nothing else would've been either), yet I was generating dozens of traces/logs each minute which sent me down this path. My final application of the function won't be HTTP triggered, but will instead be Service Bus triggered...I wonder if you foresee any problems with this? 

_**For traces:**_ 
Adding `DD_APM_IGNORE_RESOURCES` to the Function App config seems to have stopped the traces from coming in! This is absolutely amazing and has been alluding me (and DD Support) for a few months now:

![image](https://user-images.githubusercontent.com/25613680/211556447-b93d7af1-b8a3-438d-b7d2-bccdaec320cb.png)

Given that even support wasn't able to suggest this Setting, perhaps it's worth suggesting a singular document that lists all of the viable settings we can pass into serverless Function Apps. Either way, I'm thrilled to be making progress. 

_**For logs:**_ 
Given the `/admin/*` activity will still generate ~50x more log data than the function itself, I would definitely like to filter that out as well. I did indeed see the `ILogger` filter feature that was released with `v2.20.0` but can't seem to get my head around it (I'm a Python & Azure guy, just using .NET since it's the only language on Azure that has out-of-the-box APM). My confusion with the ILogger filter is that all of the documentation (including Microsoft's own) points to filtering based on log level, not a specific endpoint. I don't want to exclude _all_ Information level logs, but I do want to exclude all logs that originate from `/admin/*` activity. I did try this based on my research (highlights = my addition to existing config): 

![image](https://user-images.githubusercontent.com/25613680/211560425-f404bdff-4f07-41aa-b147-611a4f987ac9.png)

But when I added a Warning log to the function as a test, it still showed up in the logs. 

I do note that once I added that snippet to _host.json_ , I see in the logs (from DD ironically) that it is added to the LoggerFilterOptions with a Filter key, but null value: 

![image](https://user-images.githubusercontent.com/25613680/211562047-51f46a99-aac3-4a91-a877-fa14ab37c5c5.png)

I'm sure this is just a syntax problem in my _host.json_ file?

**Comment by andrewlock** [comment]
> Adding DD_APM_IGNORE_RESOURCES to the Function App config seems to have stopped the traces from coming in!

Great, glad to hear that fixed it! 🎉 

> My confusion with the ILogger filter is that all of the documentation (including Microsoft's own) points to filtering based on log level, not a specific endpoint. 

Hmmm, yes, that's generally how the `ILogger` works. _Primarily_ you filter logs based on the namespace of the component writing the log (the `CategoryName`) which means you can't generally configure the logs for a specific endpoint, like you're trying to. This is a general ASP.NET Core/Functions limitation 🤔 

FYI, I believe the `Filter` property you're seeing there is for [when you configure a filter in code](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-7.0#filter-function), which isn't possible with in-process azure functions, and wouldn't solve your issue anyway.

So the question is:

- Are _most_ of the logs coming from just a couple of specific categories, which are _only_ called in the admin endpoints? If so, you may be able to add filters for those categories so that ASP.NET Core doesn't emit those logs

Unfortunately, I don't think we actually write the category in the log message to Datadog currently, so this may be tricky to determine (I think we can/should add that). If you see the logs when testing locally (in the console) you may be able to figure that out.

If it turns out it's _not_ possible to filter these logs, you may be able to set up retention filters to simply drop most of these logs. I'm not very familiar with that side unfortunately, so it's probably best to raise a support ticket regarding that configuration if needs be.

**Comment by lucaspimentel** [comment]
Closing this issue since `SourceContext` was added in #3910 and there hasn't been any other activity since. Please re-open or create a new issue if needed. Thanks!
