### ISSUE TITLE
`dd-trace ci run` hangs on GitHub Actions in Ubuntu 20.04

### ISSUE THREAD

**Issue by cdhunt** [DataDog/dd-trace-dotnet#3826]
**Describe the bug**

We are attempting to use `dd-trace` to instrument xunit tests in dotnet in a GitHub Actions Ubuntu 20.04 runner. This has worked perfectly for us in CircleCI, but in GitHub Actions, the task gets stuck when invoking `dd-trace ci run`. There is no output, even with debugging enabled. The task just hangs indefinitely. It works fine running locally on MacOS as well.

**To Reproduce**
1. Follow [documentation](https://docs.datadoghq.com/continuous_integration/tests/dotnet/?tab=cloudciprovideragentless#instrumenting-tests)

**Expected behavior**
Should run `dotnet test`

**Runtime environment (please complete the following information):**
- Instrumentation mode: .NET tracer CLI
- OS: Ubuntu 20.04
- CLR: .NET 6

**Additional context**
It works after downgrading to version 2.22.

<!--
NOTE: To contact our support team, see https://www.datadoghq.com/support/
When contacting support, please include the information requested above.
If possible, also include the tracer log files found (by default) in:
Windows: %ProgramData%\Datadog .NET Tracer\logs\
Linux: /var/log/datadog/dotnet/
--!>

**Comment by tonyredondo** [comment]
Hi, sorry to hear that.

Can you share the `dd-trace` logs to check what's causing the hang. If you cannot share it due to sensitive data you can open a support ticket with that.

To extract the logs from the `github action` you can do the following steps before running the `dd-trace` command:

1. Ensure to set the `DD_TRACE_DEBUG` environment variable to `true`. ([Sample](https://github.com/tonyredondo/HeavyTest/blob/main/.github/workflows/dotnet.yml#L14))
2. Create the log folder and ensure write permissions for the `dd-trace` tool, by running: https://github.com/tonyredondo/HeavyTest/blob/main/.github/workflows/dotnet.yml#L33-L36

After the `dd-trace` command execution ensure to upload the logs as an artifact by using: 
https://github.com/tonyredondo/HeavyTest/blob/main/.github/workflows/dotnet.yml#L53-L57

Run the action and download the zip folder with the logs from the Summary tab.

**Comment by andrewlock** [comment]
Closing this as no response, feel free to reopen if you still have the issue!
