### ISSUE TITLE
Performance issue for each first external call every 5 minutes

### ISSUE THREAD

**Issue by Rob-Verheijen** [DataDog/dd-trace-dotnet#4117]
**Describe the bug**
We're calling HttpClient to Outlook.office365.com for example and the first call is always taking over 1 minute to execute.
Every next call within a few minutes after that first call is done in matter of seconds.

**To Reproduce**
1. Call an external link (this will take a while)
2. Call an external link again (it will now perform quickly)

**Expected behavior**
What is causing the first and following calls to be so different? And is there a way to exclude *every* external url from being profiled? I don't need to monitor external sources at this point. I don't want to blacklist every url separately if possible.

**Runtime environment (please complete the following information):**
- MSI Installer (latest)
- Tracer version: latest
- OS: Windows Server 2022
- CLR: .NET Framework 4.7.2

**Comment by lucaspimentel** [comment]
Hello, @Rob-Verheijen.

> the first call is always taking over 1 minute to execute.
> What is causing the first and following calls to be so different?

This is definitely not expected behavior. Can you open a support ticket at https://help.datadoghq.com/hc/en-us/requests/new so we can collect additional information like tracer logs or a profiler snapshot? Please reference this github issue in the ticket and include any information related to the http request that you can (for example, which method are you using to make the http request, like `HttpClient.GetStringAsync()`). Thanks!

> is there a way to exclude every external url from being profiled? I don't need to monitor external sources at this point.

Unfortunately, given a url, it's not straightforward to determine if it is an "external" resource or not. Even if we could, by the time we can inspect the url, we are already instrumenting the http request and it would probably be too late to avoid most side-effects, even if we skip creating that span.

**Comment by pierotibou** [comment]
Hello, is this issue still happening? I don't think I've seen any request going through support. Don't hesitate to contact the support if this is still happening as they will be able to collect all the needed information to proceed. Meanwhile I'll close the issue.
