### ISSUE TITLE
Instrument ASP.NET Core default HTTP library (Microsoft.AspNetCore.Http)

### ISSUE THREAD

**Issue by HitDaCa** [DataDog/dd-trace-dotnet#430]
This is a feature request to add automatic instrumentation for ASP.NET Core default HTTP library [*Microsoft.AspNetCore.Http*]. 

This default HTTP feature library is often used by application developers for exposing http endpoints when not using the MVC model.

A prominent widely used example would be [Microsoft Identity Server 4](https://github.com/IdentityServer/IdentityServer4)
The library is part of the standard [AspNet Core web framework](https://www.nuget.org/packages/Microsoft.AspNetCore.Http/) and support from version 2.x would be useful to cover most actively developed applications.

Currently the ASP.NET Core request coverage is limited to applications utilising the default MVC integration. Hover application exposing their own custom endpoints (using the ASP.NET Core default HTTP library) are currently excluded from APM.

There's currently not really a workaround I'm aware of.

**Comment by colin-higgins** [comment]
Hi, thanks for the feature request! Funnily enough that's coming very soon: https://github.com/DataDog/dd-trace-dotnet/pull/427
We will be instrumenting `HttpContext` itself from Initialize through the response disposal.

**Comment by colin-higgins** [comment]
I am closing this with the release of https://github.com/DataDog/dd-trace-dotnet/releases/tag/v1.5.0
Please let me know if it suits your needs.

**Comment by colin-higgins** [comment]
Re-opening this issue as we had to temporarily rollback the AspNetCore HttpContext instrumentation.
I will update here when we re-visit it.
(https://github.com/DataDog/dd-trace-dotnet/pull/455)

**Comment by HitDaCa** [comment]
Hi @colin-higgins,

Is there any chance you guys could instrument the common .net core HttpClient methods the same way [NewRelic .Net Core APM](https://docs.newrelic.com/docs/agents/net-agent/getting-started/compatibility-requirements-net-framework-agent) does (See #External call libraries)? This might be a possible workaround until you guys figure out the problem with the Http Context.

This would at least cover the most general http requests from an APM point of view and would allow us to fully make use of the product. Missing web requests in our APM is quite a major piece of functionality we would like/need to rely on.

**Comment by lucaspimentel** [comment]
Hey, @HitDaCa. This issue is about instrumenting the ASP.NET Core web framework. We already support automatic instrumentation for `HttpClient` ([docs](https://docs.datadoghq.com/tracing/setup/dotnet#integrations)). If you are having issues with that integration, please create a new issue for that. Thanks.

**Comment by HitDaCa** [comment]
Heya, @lucaspimentel Thanks for your reply! 
I double checked and you are absolutely correct, actual HttpClient interactions are indeed covered!
I got confused looking at the missing requests from the ASP.NET Core default HTTP library [Microsoft.AspNetCore.Http]

However, falling back to the original feature request, with the 1.6 update we are again sadly missing all web interactions which are based on ASP.NET Core default HTTP library. 
The direct consequence for us is that ~70% of our overall traffic is not monitored.
Going back to 1.5 is also not an option due to the performance impact we were also experiencing.

Could you possibly share any information with me if your team is planning on re-adding the HttpContext integration anytime soon? This feature is quite essential for us and it would be great to know if we can plan with it.

**Comment by colin-higgins** [comment]
Hey @HitDaCa 👋 
We absolutely still have this on our road-map.
The issue we experienced when adding it for the first time is that the context for `AsyncLocal` was set at a point where it was shared between many different HttpRequest pipelines.
The pattern we use for storing traces and distinguishing when to flush them expects that our storage mechanism only have one trace at a time currently. 
We have a couple different options to re-enable it:
 - Re-work our `ScopeStorage` solution
 - Begin instrumentation at a late-enough point in the pipeline

Again, it's on our roadmap, and we do hope to get back to it sooner rather than later.
We will definitely update you on this issue when we're on it.

**Comment by lucaspimentel** [comment]
@HitDaCa: We recently rewrote the ASP.NET Core integration to use the built in telemetry based on `DiagnosticSource`. With this change, we should now instrument all ASP.NET Core applications, even if they don't use MVC. This change was released in [.NET Tracer 1.12.0](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v1.12.0).
