### ISSUE TITLE
Add traces for GC

### ISSUE THREAD

**Issue by daniel-white** [DataDog/dd-trace-dotnet#511]
**Are you requesting automatic instrumentation for a framework or library? Please describe.**
- Framework or library name : .net core
- Library type: the CLR
- Library version: 1.7

**Is your feature request related to a problem? Please describe.**
I'm seeing some requests hang in my process. I can't track it down locally as its only the request span I see. It would be great to know if this is a result of stop the world GC.

**Describe the solution you'd like**
I'd like to see on my flame charts when GC occurs.

**Describe alternatives you've considered**
I'm on 2.1 and the event streams aren't available and would have been an approach in 2.2.

**Comment by macrogreg** [comment]
@daniel-white we are not currently planning to add spans for GC, it is not a logical sub-operation. You ca use ETW to trace GC behavior and we are also working on some profiling features that might help.

Notably, if your application appears to hang for a longer period of time (more than sub-seconds or more than seconds for a _very_ large memory heap), then the issue is almost certainly not GC, but something else. Perhaps a deadlock or a long running operation?

Please feel free to re-open this issue is you have questions.
