### ISSUE TITLE
Distributed tracing is impossible to implement

### ISSUE THREAD

**Issue by alexeyzimarev** [DataDog/dd-trace-dotnet#514]
In addition to #508, there is another big issue with this library.

The only way to get the tracer to work now is to use the `OpenTracingTracerFactory`. It returns a wrapper that implements `ITracer` but underneath calls the `Tracer`. So far so good, except I can't use the existing `Tracer`, so I submitted #513.

Now, I want to do distributed tracing and therefore I need to extract or inject the context from a message. I am not using http apis, I use a message broker or event streams. In `OpenTracing` library, it is quite trivial - create a text map and ask it to serialize or deserialize the dictionary. But what works fine with `OpenTracing`, suddenly starts to break with `Datadog.Trace.OpenTracing`, because it expects that I have `ICodec` implemented in my parser. That would also be ok, but this interface, like many other interfaces and classes in this library, is **internal**. So, here comes the full stop and I am unable to move anywhere.

Even if I take the code from `Datadog.Trace.OpenTracing`, which is not a lot, it again has references to the `Datadog.Trace` library own **internal** classes.

All in all, I concluded that there's no way I can ever implement distributed tracing with Datadog and being five days from the end of our trial period, where everything else is (almost) very good, this is a huge blocked for us to engage with Datadog.

**Comment by lucaspimentel** [comment]
Thanks for the feedback, @alexeyzimarev. Distributed tracing is something we definitely want to support for manual instrumentation and OpenTracing scenarios. We'll take a look and get back to you soon.

**Comment by alexeyzimarev** [comment]
So far, I managed to hack through to reach internal properties like `Span.Context` and so on, using reflections. Not nice, but hopefully I can make it work.

**Comment by ghelyar** [comment]
With so much of `Datadog.Trace.OpenTracing` being no-ops, as far as I'm concerned, it's currently not fit for purpose anyway.

I spent a while trying to work out why my baggage and logs weren't working, only to find out that the implementations are missing, but they don't throw `NotImplementedException`s or anything like that, [they just pretend to work and silently do nothing](https://github.com/DataDog/dd-trace-dotnet/blob/master/src/Datadog.Trace.OpenTracing/OpenTracingSpan.cs ) so you think you've logged something but you haven't. These features were the only reason I was trying to use `Datadog.Trace.OpenTracing` in the first place, and since they don't exist I can't see any reason to use `Datadog.Trace.OpenTracing` over `Datadog.Trace` at all. 

So I tried to just use `Datadog.Trace`, only to find that I can't propagate the sampling priority when using manual instrumentation because both `Span`'s `SpanContext` and the `SpanContext`'s `TraceContext` are internal properties. The sampling priority can be set either through an extension method or a tag, but then can't be read afterwards. Both of these methods of setting it seem like workarounds to the real problem, which is that too much of the library is internal, so as soon as you try to do anything more than copy-paste an example from the documentation you hit a brick wall that you need to use reflection to overcome.

Having `TraceId` and `SpanId` as `ulong`s also makes it hard to integrate with other things. For example, https://www.w3.org/TR/trace-context/ suggests using 32 hex digits (a 128 bit number) for the trace ID, which is too long for a `ulong`, so it's hard to integrate into Datadog. The same thing goes for anything that would use a GUID. Using strings instead of ulongs would allow better compatibility.

**Comment by lucaspimentel** [comment]
Thanks for the feedback, @ghelyar. We're sorry about your frustration with the tracer library. I'll try to address some of your concerns here:

> so much of `Datadog.Trace.OpenTracing` being no-ops...
> baggage and logs [...] implementations are missing, but they don't throw `NotImplementedExceptions` or anything like that, they just pretend to work and silently do nothing

We are going to update our documentation to more clearly state which OpenTracing methods are not currently supported. Throwing `NotImplementedException` from these methods is not an option. This would make the library unusable for many of our OpenTracing users that combine it with 3rd party instrumentation.

> I can't see any reason to use `Datadog.Trace.OpenTracing` over `Datadog.Trace` at all.

Many users prefer to write code against the standard interfaces provided by [OpenTracing](https://github.com/opentracing/opentracing-csharp) instead of having explicit dependencies on one APM vendor's tracer.

Another use for the OpenTracing tracer is to combine it with instrumentation libraries like [`OpenTracing.Contrib.NetCore`](https://github.com/opentracing-contrib/csharp-netcore). This 3rd party library provides automatic instrumentation of "any library or framework that uses .NET's `DiagnosticSource` to instrument its code." This includes ASP.NET Core MVC, SqlClient, HttpClient, Entity Framework Core, and others.

>  I can't propagate the sampling priority when using manual instrumentation

Not being able to _read_ distributed tracing details from a span was an oversight in the manual instrumentation library which we will fix soon. Like I said in a previous comment above, this should be supported for manual instrumentation and OpenTracing scenarios, not only automatic instrumentation. It's a bug and this GitHub issue serves as the bug report.

> the real problem [...] is that too much of the library is internal.

This encapsulation is intentional. Not making everything `public` allows us to make large changes to the tracer code without breaking existing user code. It also prevents users from breaking things by using the code in unsupported ways. Anything we make `public` has a cost: it needs to be supported, documented, and kept around in future versions indefinitely.

> A good start would be removing those `InternalsVisibleTo` attributes at least for non-test libraries and see how far you get.

This is a great idea and something we can definitely use when we address this GitHub issue.

> Having `TraceId` and `SpanId` as `ulong`s also makes it hard to integrate with other things. For example, https://www.w3.org/TR/trace-context/ suggests using 32 hex digits (a 128 bit number)...

For the time being, our back-end only supports 64-bits for `TraceId` and `SpanId`. This applies to all our language tracers, not only dotnet. Removing this limitation is on our roadmap.

**Comment by alexeyzimarev** [comment]
@lucaspimentel I want to follow up on this:

> This encapsulation is intentional. Not making everything public allows us to make large changes to the tracer code without breaking existing user code. It also prevents users from breaking things by using the code in unsupported ways.

I understand that. However, the library currently only supports http headers for the context transfer. It is quite naive to assume that the only thing people use in distributed systems is HTTP. We put OpenTracing context when storing events, publish messages to the broker and quite a few other use cases. Now, since the `OpenTracingTracer` _only_ supports the `ICodec` **internal** interface implementation for both `Inject` and `Extract`, it is **impossible**.

To add insult to injury, such an implementation clearly violates the LSP, because when I send the valid `IFormat<TCarries>` as a parameter, the Datadog implementation just blows up with an unsupported exception.

**Comment by alexeyzimarev** [comment]
I have checked the whole thing closer and I now understand that as soon as I give the Datadog tracer the http header built-in format (`BuiltinFormats.HttpHeaders`) it will use it. Maybe, just adding the same `HttpHeaderCodec` to the `_codecs` dictionary for the `BuiltinFormats.TextMap` would be a very good step forward. The OpenTracing .NET lib has just two built-in formats and if both of them are supported - I personally would be happy.

In the future, I'd love to see something similar to the extractor/injector registry like in Jaeger library, but that's a bit more work.

**Comment by lucaspimentel** [comment]
@alexeyzimarev: Thanks for the feedback! I understand that this is a real pain point right now. If there's a specific change that would make things easier (you mentioned "adding the same `HttpHeaderCodec` to the `_codecs` dictionary" above?), we do accept community contributions. In the meantime, we'll see what we can do about prioritizing distributed tracing support in OpenTracing.

**Comment by alexeyzimarev** [comment]
I will submit a PR for the TextMap built-in formatter that will use the same codec. I started using it by specifying the HttpHeaders built-in formatter, deleted all my forked code and it all works, so I think it's completely safe to use the same formatter for both. There're no HTTP-header specific code in your text map implementation as far as I can see.

**Comment by alanisaac** [comment]
@lucaspimentel any word on this?  

We're evaluating different tracing providers, and the lack of support for `BuiltinFormats.TextMap` in this library is preventing us from evaluating Datadog (without changing all downstream code where we inject with that format).

I'm happy to look at submitting a PR if it's not in conflict with active work.

**Comment by lucaspimentel** [comment]
This unintentionally got closed when I merged #677. Reopening until we release those changes.

**Comment by lucaspimentel** [comment]
@alanisaac added support for `BuiltinFormats.TextMap`. Closing this issue since that change was included in [release 1.16.0](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v1.16.0).
