### ISSUE TITLE
Image "gcr.io/datadoghq/dd-lib-dotnet-init:latest" NotFound desc = failed to pull and unpack image "gcr.io/datadoghq/dd-lib-dotnet-init:latest": no match for platform in manifest: not found

### ISSUE THREAD

**Issue by shashiranjan84** [DataDog/dd-trace-dotnet#5321]
**Describe the bug**
Started getting this error few hours back

**Comment by shashiranjan84** [comment]
Seems like you missing image for `[linux/arm64](https://hub.docker.com/r/datadog/dd-lib-dotnet-init/tags)`

**Comment by bparentpichette** [comment]
@shashiranjan84 
You means "linux/amd64" 
The "linux/arm64" block is [here](https://console.cloud.google.com/artifacts/docker/datadoghq/us/gcr.io/dd-lib-dotnet-init/sha256:24cb87e1fe2f616d7ded0ed26616ea6b463fff587235b21efc4e57dd0c0fdef1;tab=manifest) 

But same problem for me. I'm facing this error trying to get the image

**Comment by corentinaltepe** [comment]
Hi, I met the same issue. I was using the `latest` tag and [this image pushed yesterday](https://hub.docker.com/layers/datadog/dd-lib-dotnet-init/latest/images/sha256-90fb2d3cfd0cfa2a742007c82ca9a3b8974381cccdfc11d11908ee0abb66ca2b?context=explore) doesn't support `linux/amd64`. In the meantime, I had to use the tag `v2.48.0` instead of `latest`.

**Comment by shashiranjan84** [comment]
Seems like they pushed the image for `linux/amd64` [today](https://hub.docker.com/r/datadog/dd-lib-dotnet-init/tags). Closing the ticket

**Comment by andrewlock** [comment]
Apologies about that, you're right, we didn't realize there was an issue with `buildx` `v0.13.0` causing this. We pinned at `v0.12.1` and resolved the issues. Thanks for notifying us and sorry for the inconvenience
