### ISSUE TITLE
ASP.NET Core 3.1 APM affected by Serilog.MinimumLevel.Override

### ISSUE THREAD

**Issue by mustafasturan** [DataDog/dd-trace-dotnet#578]
**Describe the bug**

We are using Serilog for logging purposes. When we override MinimumLevel with this code 
 .MinimumLevel.Override("Microsoft", LogEventLevel.Warning)
 ASP.NET Core APM stops working but others StackExhange.Redis and SqlClient Apms are not affected.

**Runtime environment (please complete the following information):**

- Instrumentation mode: automatic with Nuget Package
- Tracer version: 1 .1.10
- OS: docker on ubuntu image: mcr.microsoft.com/dotnet/core/aspnet:3.1-bionic
- CLR: ASP.NET Core 3.1

**Comment by lpodolak** [comment]
I am experiencing exactly same problem. Right now I am unable to achieve both:
1) have automated apm instrumentation for my asp.net core app
2) do not pollute my output logs with "Microsoft" logs - I believe you also do it for the same reason.

I did some attempts and I found that I need to leave "Microsoft.AspNetCore.Mvc.Infrastructure" logs in order to have dd logs. Once raising the level of these entries to Warning, automatic asp.net core apm stops working.

@mustafasturan did you find any workaround?

**Comment by fehmianac** [comment]
Hi @lpodolak,

I am working with mustafasturan. 

APM is working listening log of "Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker". So when you add "MinimumLevelOverride" to Serilog APM is losing data source and you can not show any trace on Datadog.

Our work around working like that.

Our system is still creating Microsoft logs but we don't sink anywhere. So Datadog can tracing our system but doesn't collect Microsoft logs. It works for our case. 

1-) You should create WrapperSink.cs in your project.

    public class WrapperSink : ILogEventSink
    {
        private readonly ILogEventSink _logEventSink;

        public WrapperSink(ILogEventSink logEventSink)
        {
            _logEventSink = logEventSink;
        }

        public void Emit(LogEvent logEvent)
        {
            if (logEvent.Properties.TryGetValue("SourceContext", out var sourceContext))
            {
                if (sourceContext.ToString().StartsWith("\"Microsoft"))
                {
                    return;
                }

                if (sourceContext.ToString().StartsWith("\"System"))
                {
                    return;
                }
            }

            _logEventSink.Emit(logEvent);
        }
    }

    public static class WrapperSinkExtensions
    {
        public static LoggerConfiguration WrappedSink(this LoggerSinkConfiguration lsc, Action<LoggerSinkConfiguration> writeTo, LogEventLevel logEventLevel = LogEventLevel.Information, LoggingLevelSwitch loggingLevelSwitch = null)
        {
            return LoggerSinkConfiguration.Wrap(lsc, wrapped => new WrapperSink(wrapped), writeTo, logEventLevel, loggingLevelSwitch);
        }
    }

2-) You should add ConsoleSink like that


    var loggerConfiguration = new LoggerConfiguration()
    loggerConfiguration.WriteTo.WrappedSink(l => l.Console(new CompactJsonFormatter()));

**Comment by lpodolak** [comment]
Thank you @fehmianac and @mustafasturan 
Your solution did help me to get rid of this trap, though I did a bit different solution, though basing on the same assumption: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker log events can not be muted by override.

Instead of creating a wrapping logger, I used Serilog's sub logger functionality (via .Logger() method):

          .Log.Logger = new LoggerConfiguration()
                // root logger configuration here
                .WriteTo.Logger(rootConfig => rootConfig
                    .Filter.ByExcluding(e => e.ShouldExcludeForConsole(loggingOptions.Sinks.Console))
                    .WriteTo.Console(outputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3} {SourceContext}] {Message:lj}{NewLine}{Exception}")
                )
                .WriteTo.Logger(rootConfig => rootConfig
                    .Filter.ByExcluding(e => e.ShouldExcludeForRedis())
                    .WriteTo.RedisList(redisListOptions.RedisUris, SerilogExtensions.GetRedisListKeyName(environment))
                )
                .CreateLogger();`

I am using .Filter here to to mute "Microsoft" logs in subloggers instead of MinimumLevel.Overrdie() as the latter unfortunately doesn't work with sub-loggers, though - it is present in the api - iit only works at a root level (https://github.com/serilog/serilog/pull/1033).
This way, I am sending correctly filtered logs to both my sinks (Console and Redis) while I leave the Microsoft log events be emitted by the root logger - and so they can be reached by datadog tracer.

The filtering is done basing on the "SourceContext" property that each event has (similar to fehmaniac's example):

` e.Properties.TryGetValue("SourceContext", out var sourceContext);`

So this is a workaround to this problem but only when having Serilog plugged into the pipeline. I didn't have it there, so I needed to let it control the entire asp.net core logging. I wonder what is the workaround for those who don't use it this way?

**Comment by andrewsouthard1** [comment]
Hey all - as an update here we expect to address these in our next release. We're targeting later this week or early next.

**Comment by lucaspimentel** [comment]
Hello all. We released [.NET Tracer 1.12.0](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v1.12.0) which includes a complete rewrite of the ASP.NET Core instrumentation to use the telemetry that is built into the framework. This should resolve the missing traces in ASP.NET Core 3.1.

**Comment by lpodolak** [comment]
Thanks, I'll try to upgrade in next few weeks, as right I have other priorities and working workaround. I will report back here when I do it if everything's okay.

**Comment by lpodolak** [comment]
We successfully upgraded to DataDog 16.1.2 with .net core 3.1 and I confirm that the problem is gone. 👏
