### ISSUE TITLE
Datadog.Trace.ClrProfiler.Managed marked obsolete in version 1.11.0

### ISSUE THREAD

**Issue by owensearls** [DataDog/dd-trace-dotnet#619]
**Describe the bug**
The most recent version of the Datadog.Trace.ClrProfiler.Managed nuget package is marked obsolete, but is still recommended in your documentation here https://docs.datadoghq.com/tracing/setup/dotnet/?tab=netcoreonlinux. 

The description of this package also suggests using the Datadog.Trace.AspNet package, but that package is only marked as compatible with .NETFramework 4.5.

Do you have a recommendation for the best way to set up tracing for a .NET Core 3 application?

**Runtime environment (please complete the following information):**
- Instrumentation mode: automatic
- Tracer version: 1.11.0
- OS: linux
- CLR: .NET Core 3.1

**Additional context**

**Comment by ymko13** [comment]
Having a similar issue right now, made a few assumptions here and there but can't get automatic instrumentation to work for .Net Core 3.1 MVC application with IIS on Windows. 

Some of the assumptions:
1. I have only added Datadog.Trace (1.11.0) as a reference. 
2. My app settings are in datadog.json and seem to be read just fine
`{
  "DD_TRACE_AGENT_URL": "http://localhost:8126",
  "DD_ENV": "Local",
  "DD_SERVICE_NAME": "<actual service name here>",
  "DD_LOGS_INJECTION": "true",
  "DD_TRACE_ENABLED": "true",
  "DD_TRACE_ANALYTICS_ENABLED": "true",
  "DD_AspNetCoreMvc2_ENABLED": "true",
  "DD_AspNetCoreMvc2_ANALYTICS_ENABLED": "true",
  "DD_AspNetWebApi2_ENABLED": "true",
  "DD_AspNetWebApi2_ANALYTICS_ENABLED": "true",
  "DD_ElasticsearchNet_ENABLED": "true",
  "DD_ElasticsearchNet_ANALYTICS_ENABLED": "true",
  "DD_TRACE_DEBUG": "true",
  "DD_DOTNET_TRACER_HOME": "C:\\Program Files\\Datadog\\.NET Tracer\\"
}`
3. I have tested manual instrumentation and i can see that on the other side (on datadog website).
4. I have also connected logging with Serilog, however i noticed the issue #578 and not overriding the MinimumLevel anymore. 

I have not tried it on Linux yet, but I presume i would have a similar issue. 

Runtime:
- Instrumentation mode: automatic
- Tracer version: 1.11.0
- OS: Windows
- CLR: .NET Core 3.1

**Comment by lucaspimentel** [comment]
Thanks for the feedback @owensearls. With the release of .NET Tracer 1.12.0 last night, we have update the NuGet package text to better explain the changes and steps for users going forwards.

We are also in the process of updating the documentation to update references to the NuGet packages.

To clarify: `Datadog.Trace.AspNet` is no longer required to automatically instrument "legacy" ASP.NET (as of `1.12.0`), and `Datadog.Trace.ClrProfiler.Managed` is no longer required for any automatic instrumentation on .NET Core (since `1.8.0`). Both packages are now deprecated and empty. You can remove them from you apps when you update to the latest version of .NET Tracer.
