### ISSUE TITLE
StartActive no longer sets ActivateSpan in v3

### ISSUE THREAD

**Issue by jvalore-bestegg** [DataDog/dd-trace-dotnet#6414]
**Describe the bug**
This is probably intentional in the breaking changes from v2 to v3, but it's unclear how to resolve it...

Using `v2.60.0` this xunit test would pass:

```
    [Fact]
    public void StartActiveShouldSetActiveScope()
    {
        Tracer.Instance.ActiveScope.Should().BeNull();
        var scope = Tracer.Instance.StartActive("test");
        Tracer.Instance.ActiveScope.Should().NotBeNull();
    }
```

In `v3.6.1` the test no longer passes. `Tracer.Instance.ActiveScope` remains `null`

**To Reproduce**

Create a new xunit project:

```
mkdir DDTraceTest
cd DDTraceTest
dotnet new xunit
dotnet add DDTraceTest.csproj package FluentAssertions
dotnet add DDTraceTest.csproj package Datadog.Trace.Bundle
```
Open the generated `UnitTest1.cs` and add the test code from above ⏫ 

```
dotnet test
```
will fail:
```
[xUnit.net 00:00:00.08]   Finished:    DDTraceTest
  DDTraceTest test failed with 1 error(s) (0.4s)
    /Users/jeff.valore/Projects/DDTraceTest/UnitTest1.cs(14): error TESTERROR:
      DDTraceTest.UnitTest1.StartActiveShouldSetActiveScope (25ms): Error Message: Expected Tracer.Instance.ActiveScope not to be
      <null>.
```

Open `DDTraceTest.csproj` and change the `Datadog.Trace.Bundle` reference to `2.60.0`
```
<PackageReference Include="Datadog.Trace.Bundle" Version="2.60.0" />
```

```
dotnet test
```
will pass:
```
  DDTraceTest test succeeded (0.5s)

Test summary: total: 1, failed: 0, succeeded: 1, skipped: 0, duration: 0.5s
Build succeeded in 1.1s
```

**Expected behavior**
Expected that calling `Tracer.Instance.StartActive` would set `Tracer.Instance.ActiveScope`

Or maybe it no longer does in v3? But the migrating from v2->v3 doc isn't clear on what is supposed change to make this code still pass.

**Screenshots**

**Runtime environment (please complete the following information):**
- Instrumentation mode: [e.g. automatic with msi installer or manual with NuGet package]
- Tracer version: 3.6.1
- OS: MacOS (M3)
- CLR: .NET core 9 `<TargetFramework>net9.0</TargetFramework>`

**Additional context**

<!--
NOTE: To contact our support team, see https://www.datadoghq.com/support/
When contacting support, please include the information requested above.
If possible, also include the tracer log files found (by default) in:
Windows: %ProgramData%\Datadog .NET Tracer\logs\
Linux: /var/log/datadog/dotnet/
--!>

**Comment by andrewlock** [comment]
Hi @jvalore-bestegg, yes, in the scenario you're describing, you're trying to do manual-only instrumentation, which is no longer supported in v3. In order for this to work you need to also use automatic instrumentation, which "enables" it. I realise this isn't ideal for the test scenario you're describing here, creating scopes in a test project, as it's probably unlikely you _want_ automatic instrumentation there in general🤔 Doing "real" tracing would create the spans and traces, but you wouldn't be able to send them to the Datadog agent unless that was configured, which may cause 

The one exception to that would be if you are using Datadog's [Test Visibility product](https://docs.datadoghq.com/tests/setup/dotnet/?tab=ciproviderwithautoinstrumentationsupport). In this scenario,  you _do_ get automatic instrumentation, so that test would pass.

I think the only suggestions we have right now are:

- Use an abstraction (e.g. `ITracer`, implemented by `Tracer`) in your app instead of calling `Tracer.Instance` directly, so that you can Moq/Stub the calls as required.
- Use `Activities` and OTel instead of Datadog.Trace. In production we can interoperate with `Activities` so this will still work much like before, but it would require changing your calling code.
- Use the Test Visibility product (this instruments your test application, sends traces to Datadog, and allows features like flaky test discovery, intelligent test runner, code coverage etc).

From my point of view, I would recommend the first option i.e. register `ITracer` with the DI container, and use a stub implementation in tests. I find this preferable as you probably don't _want_ to be sending traces you create in your test suite to Datadog (unless you're using Test Visibilty), so using a stub/moq in those cases makes the most sense.

We'll make sure to call out this limitation related to testing explicitly in our migration guide, and will consider whether there are other options to make this scenario easier.

**Comment by mikesigs** [comment]
@andrewlock We have a bunch of custom tracing logic that we can no longer run tests against (easily). I suppose we could use the `dd-trace` tool to run the tests from the CLI or Docker, but we can't easily run them within Visual Studio anymore. This feels like a bit of an oversight on the "No custom tracing only" decision. Any chance your team could reconsider and support this for testing scenarios? Or perhaps you could recommend an existing solution for Visual Studio's test runner to enable automatic tracing? Thanks!

**Comment by andrewlock** [comment]
> We have a bunch of custom tracing logic that we can no longer run tests against (easily)

Hi @mikesigs, would it be possible to show what these tests look like in practice? Are you doing "end-to-end" testing of tracing logic, or is it more modular testing based on shared tracing primitives etc? 

For example, how where/were you doing assertions? e.g. are you confirming that calling a certain method adds a set of tags? Or are you trying to assert against the actual serialized span data? Or the data that appears in Datadog?

One of the problems of the previous test story was that it was very difficult to do correctly, would behave differently in different scenarios, and could easily cause performance issues. If we can get a good understanding of exactly which aspects you're trying to test, we can look at potential solutions to make it easier 🙂 Thanks!

**Comment by mikesigs** [comment]
The custom tracing logic was heavily inspired by Jimmy Bogard's series on end-to-end diagnostics with NServiceBus. (for [reference](https://www.jimmybogard.com/building-end-to-end-diagnostics-and-tracing-a-primer/))

I built a bunch of behaviors and other middleware to enable distributed tracing from ASP.NET Web API <-> NServiceBus. It has worked very well for us for a few years. It predates a stable version of OTel (if you were wondering why we don't just use that). The plan is to migrate to OTel soon, but for now it's not high on the priority list.

Now that we are upgrading things to .NET 9, we're finding these tests are no longer working. Unfortunately, it's been the biggest stumbling block in our upgrade.

The tests themselves are ensuring tags are set properly, that parent scope is propagated from headers, and things like the Operation Name are set by the behavior properly. On Friday I was able to refactor the behaviors to take an injected ITracer instead of using the static instance. This was helpful, as it let me fix the tests to use a custom FakeTracer implementation. However, I cannot seem to easily get the Parent scope logic working in the FakeTracer. I didn't try using mocks, but I don't think that will work either because Parent isn't an interface property. I wound up just removing the Parent logic from the tests. 

So that's where I'm at right now. The tests are passing using the FakeTracer, but I'm no longer able to test the Parent logic. I'm also not completely satisfied that the tests are especially useful anymore, as they're really more integration tests to ensure that our custom tracing implementation works as expected with DataDog.
