### ISSUE TITLE
High CPU usage when using manual tracing

### ISSUE THREAD

**Issue by yohanb** [DataDog/dd-trace-dotnet#649]
**Describe the bug**
When using manual tracing inside with .NET core application, the CPU spikes to near 100% when traces are numerous (500/s).

**To Reproduce**
1. Setup manual tracing in dotnet core app
2. Trace repeatedly

**Expected behavior**
A negligible raise in CPU activity.

**Screenshots**
![image](https://user-images.githubusercontent.com/812993/74968991-ccff7300-53e9-11ea-9c5a-62f40ee09951.png)

**Runtime environment (please complete the following information):**
- Instrumentation mode: manual with NuGet package (Datadog.Trace 1.12) and automated with Core CLR profiler
- Tracer version: 1.12
- OS: Ubuntu 16.04
- CLR: .NET Core 3.1

**Additional context**
Support ticket #308803

**Comment by macrogreg** [comment]
Hi @yohanb ,

We have made a ton on perf improvements in the recent months. Please check out:
https://github.com/DataDog/dd-trace-dotnet/releases

Are also are continuing with a very significant, ongoing perf improvement effort.

Please also note that when you measure CPU in % rather than in micro-cores there are some caveats to take into consideration.
For example, if your application does very little overall and the CPU usage is close to zero, CPU tends to "get busy", when the process is starting to do work. Especially, when you start creating 500 spans / sec. :)

In order to look into the details of this, we would need some detailed information about your test application.

Given the ongoing work in this area, I will close this particular issue right now. Please feel free to re-open if you would like to add some additional information. 

Thanks!
