### ISSUE TITLE
Instrument System.Net.Http.SocketsHttpHandler

### ISSUE THREAD

**Issue by shields478** [DataDog/dd-trace-dotnet#668]
**Are you requesting automatic instrumentation for a framework or library? Please describe.**
- Framework or library name : System.Net.Http.SocketsHttpHandler
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler

**Is your feature request related to a problem? Please describe.**
There's no auto instrumentation for System.Net.Http.SocketsHttpHandler and we would like to utilize this class over the existing ones (System.Net.Http.HttpClientHandler & System.Net.Http.HttpMessageHandler)

**Describe the solution you'd like**
Similar auto instrumentation for SocketsHttpHandler

This looks like it may have been looked into before as I've see some docs here: https://github.com/DataDog/dd-trace-dotnet/commit/129cce22056239f38622452399aacf6166adeadb

Is this somethings that is still in the works?

**Comment by andrewsouthard1** [comment]
@shields478 Thanks for reaching out here - this feature is currently on our radar for development over the next month. We'll keep you updated here as we get closer.

**Comment by lucaspimentel** [comment]
I think the only code change required is to allow `SocketsHttpHandler` [in this `if` statement](https://github.com/DataDog/dd-trace-dotnet/blob/9cfca307cc9253c04869fe2cb81fcb008893ce9f/src/Datadog.Trace.ClrProfiler.Managed/Integrations/HttpMessageHandlerIntegration.cs#L174). Note that this would create an additional child span under `HttpClientHandler` on every app running in more recent versions of .NET Core, since `HttpClientHandler` now uses `SocketsHttpHandler` under the hood, if I remember correctly.


```diff
+if (!(handler is HttpClientHandler) || !IsTracingEnabled(request))
-if (!(handler is HttpClientHandler || handler is SocketsHttpHandler) ||  !IsTracingEnabled(request))
{
    // skip instrumentation
    // ...
}
```

**Comment by zacharycmontoya** [comment]
Hi @shields478 , we just released [.NET Tracer 1.16.1](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v1.16.1) which includes this new integration behind the opt-in flag `DD_HttpSocketsHandler_ENABLED=true`. It's opt-in for now with plans to include it by default soon. I'm going to close this issue now but let us know if you have further questions
