### ISSUE TITLE
Unhandled exception. System.EntryPointNotFoundException: Unable to find an entry point named 'GetAssemblyAndSymbolsBytes'

### ISSUE THREAD

**Issue by sclassymiller** [DataDog/dd-trace-dotnet#727]
**Describe the bug**
We have Contrast profiler chained with DataDog. The contrast agent runs first and then DataDog. The application framework is .Net Core 3.1 with DataDog 1.16.0 and Contrast.SensorsNetCore 1.5.0 tied to the issue. I was able to resolve the issue by downgrading to 1.6.2 of DataDog. I tried DataDog 1.10.0-1.16.0 and none of those releases resolved the issue I am facing. 
 
**To Reproduce**
1. Follow these instructions: https://docs.contrastsecurity.com/installation-netcoreinstall.html for .Net Core and Linux
2. Make sure you have configured DataDog 1.16.0 and Contrast Security Scanner 1.5.0 to your Dockerfile
3. Chain DataDog and Contrast together
4. Build and run your docker file and notice the entry point error 
5. Downgrade DataDog to 1.6.1 -> Notice the error isn't present

**Expected behavior**
Both APMs working together without any issues

**Screenshots**
`Unhandled exception. System.EntryPointNotFoundException: Unable to find an entry point named 'GetAssemblyAndSymbolsBytes' in shared library '/opt/Contrast.Net.Core_1.5.0/runtimes/linux-x64/native/ContrastProfiler.so'.
   at __DDVoidMethodType__.GetAssemblyAndSymbolsBytes(IntPtr& , Int32& , IntPtr& , Int32& )
   at __DDVoidMethodType__.__DDVoidMethodCall__()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder..ctor()
   at Microsoft.AspNetCore.WebHost.CreateDefaultBuilder(String[] args)`

**Runtime environment (please complete the following information):**
- Instrumentation mode: https://www.nuget.org/packages/Contrast.SensorsNetCore/ 
- Tracer version: 1.10.0-1.16.0
- OS: Linux
- CLR: .Net Core 3.1

**Additional context**
About Contrast Profiler Chaining
Contrast profiler chaining allows the .NET Core agent to run alongside another .NET Core APM profiler, such as the ones provided by AppDynamics or New Relic.

To achieve profiler chaining, you should replace the CORECLR environment variables for the APM with CONTRAST_CCC_CORECLR versions. Any of the following environment variable names that exist should be transformed:

CORECLR_PROFILER -> CONTRAST_CCC_CORECLR_PROFILER
CORECLR_PROFILER_PATH -> CONTRAST_CCC_CORECLR_PROFILER_PATH
CORECLR_PROFILER_PATH_32 -> CONTRAST_CCC_CORECLR_PROFILER_PATH_32
CORECLR_PROFILER_PATH_64 -> CONTRAST_CCC_CORECLR_PROFILER_PATH_64

**Comment by m0nkey653** [comment]
Hi, I'm responding on the behalf of Contrast Security. The Contrast .NET agent employs a chaining technique to get around the single profiler per process limitation in the CLR. The Contrast agent is loaded by the CLR using the environment variables the CLR expects. The Contrast agent then loads the chained profiler via chained environment variables (Example: `CONTRAST_CCC_CORECLR_PROFILER_PATH_64={chained-profiler-path.dll}`).

It looks like in `dd-trace-dotnet` version 1.7, the profiler started using the `CORECLR_PROFILER_PATH` environment variables to get a path to its profiler shared library on Linux to get an export - `GetAssemblyAndSymbolsBytes`. Since the Contrast profiler is set in that environment variable, the entry point is not found and we get the crash noted here.

https://github.com/DataDog/dd-trace-dotnet/blob/v1.7.0/src/Datadog.Trace.ClrProfiler.Native/cor_profiler.cpp#L808-L829

The Contrast team is looking into the issue now.

**Comment by m0nkey653** [comment]
The Contrast team has addressed this issue and the fix will be in the next Contrast.NET Core Agent release. The Contrast agent will reset these environment variables to Datadog profiler filepath.

**Comment by macrogreg** [comment]
Hi @sclassymiller 

Looks like the issue has been addressed. I will close it for now. Please feel free to reopen if you have additional questions.

(Please note in this context: while we are doing our best to seamlessly fit into any environment where your application is running, Datadog does not officially support scenarios where multiple profilers are attached to your process.)
