### ISSUE TITLE
Http client integration sometimes times out sending data

### ISSUE THREAD

**Issue by yohanb** [DataDog/dd-trace-dotnet#754]
**Describe the bug**
Seems that I sometimes see the http-client integration timing out after 60 seconds (task timeout) when trying to send trace data to Datadog.

**To Reproduce**
N/A

**Expected behavior**
Better timeout handling or retry mechanism.

**Screenshots**
![image](https://user-images.githubusercontent.com/812993/84693912-47fb1500-af16-11ea-9f67-ceb91f24f987.png)

**Runtime environment (please complete the following information):**
- Instrumentation mode: automatic
- Tracer version: 1.17
- OS: Ubuntu 16.04
- CLR: .NET Core 3.1

**Comment by macrogreg** [comment]
Hi @yohanb ,

> Seems that I sometimes see the http-client integration timing out after 60 seconds (task timeout) **when trying to send trace data to Datadog**.

Can you please clarify why you say "_when trying to send trace data to Datadog_"? We instrument HttpClient generally to be able to create spans that describe your application's remote calls. This is for _any_ remote call. The provided stack trace looks like your application is doing some communication using HttpClient, and whatever communication is happening, it is timing out. Datadog is on the stack, because we created the span.

In order to investigate this further, can you please provide some additional information:
* What remote call was the application doing the the exception happened?
* Does problem ever occur without the datadog tracer being active?

Thank you!

**Comment by yohanb** [comment]
hi @macrogreg ,
if I understand correctly, you are saying that this error is normal if the remote call that is being instrumented times out?  The way I read the error was as if communication with Datadog's API was timing out while trying to send instrumentation data.

**Comment by macrogreg** [comment]
@yohanb ,  the error seems unrelated to being instrumented.

Is the stack you provided in the above screenshot complete?
I.e. who invoked `SendAsyncInternal(..)` in this case: 

![image](https://user-images.githubusercontent.com/20691812/96054355-54e13400-0e36-11eb-9dfa-7ecb2f501673.png)

I am guessing (we need to confirm by looking at the full stack), that it is application code. In that case, what is happening is that your application simply places a call using HttpClient and we instrument the client so that we can emit spans. The timeout occurs because your requested URL times out.

In order to see whether this analysis is correct or not, we need a full stack trace. :)

In parallel, if possible, please consider upgrading the latest release:
https://github.com/DataDog/dd-trace-dotnet/releases

In case that the analysis is _not_ correct, you will be able to take advantage of several recent improvements in how we send traces.

**Comment by yohanb** [comment]
@macrogreg thanks for the info!  We'll update to the latest version and see what happens.
