### ISSUE TITLE
Make IAgentWriter Interface public

### ISSUE THREAD

**Issue by warren-schay** [DataDog/dd-trace-dotnet#835]
**Describe the solution you'd like**
Allow for the IAgentWriter interface (and therefore AgentWriter) to be public to allow for complete traces (or even multiple traces) to be sent to the agent without having to make use the realtime StartSpan functionality

**Additional context**
I have an application that already has an internal tracing mechanism. I would like to be able to send the completed traces to Datadog via the .net tracer by converting the bespoke tracing structure to the pre-requisite Span structure

**Comment by macrogreg** [comment]
Hi @warren-schay ,
Can you please describe your requirements a little better?

We are currently looking into using the .NET built-in Activity APIs to describe spans. In that scenario you would be able to use [ActivitySource ](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.activitysource?view=net-5.0) to start and stop spans and they would be sent to the backend. 

If you have some other tracking meachanism that is not related to .NET Activities, you could use your own custom code to listen to the event when your internal activities are started and later stopped and you would translate them to respective Activity-related API calls.

Please note that you can already do something similar with he current tracing APIs. If this approach does not work for you, can you please provide some more details about your system, so that we can better understand your scenarios?

**Comment by macrogreg** [comment]
Hi @warren-schay ,

I have not heard back from you in a while, so I will close the issue for now.
However, please feel free to reopen if you have additional information.

Thank you!
