### ISSUE TITLE
Make IScopeManager public and the Tracer constructor that inputs scope managers public 

### ISSUE THREAD

**Issue by warren-schay** [DataDog/dd-trace-dotnet#836]
**Describe the solution you'd like**
Allow for custom scope managers to be provided to the Tracer by making the IScopeManager public and the Tracer constructor that inputs scope managers to be also public 

**Additional context**
Due to the the threading mechanism of my application, the default ScopeManager is not able to keep context correctly of a call. I would like to be able to write a custom Scope Manager that is aware of my internal operational context and therefore be able to correctly track a trace

**Comment by macrogreg** [comment]
Hi @warren-schay ,

Could you please provide some details around how you use threading that does not work well with the current system?

**Comment by warren-schay** [comment]
Hi,

Thanks for the reply and apologies for my delay. I seem to have gotten
around this issue myself.
Essentially the system queues up all items of work (using a .net queue) and
then using a thread-pool, each item is picked up and the contained delegate
run.

I had to manually track the scope between the workitem being queued and
then subsequently run. Once in the running thread - the DD tracer managed
to keep track of the scope.

Regards,

Warren

**Comment by macrogreg** [comment]
Hi @warren-schay ,

Thank you for your response. 

When you call an async API, the trace context is flown automatically (e.g. `await client.CallRemoteApiAsync()`). This is because such calls typically are a part of your distributed transaction. 

When you explicitly schedule a parallel (rather than async) operation (e.g. `Task.Run( () => MyMethod(state) )`), the trace context is not flown. This is because such operations tend to start background operations that are not a part of the request-response cycle. Typically. true sync operations are preferred. If an API does not offer an async version, a synchronous invocation is preferable: Offloading it to the thread pool will not save you any throughput-relevant resources. Of course, there may be a need for such invocations that _are_ part of a request, but it is relatively rare in server applications. If you have such a case, it appears that you have already discovered a workaround. 

I will go ahead and close this issue for now. If you have additional questions on this topic, please feel free to re-open it.

Thank you!
